### ISSUE TITLE
Scroll over the vertical panel to see the hidden apps

### ISSUE THREAD

**Issue by gadass** [home-sweet-gnome/dash-to-panel#1028]
Dear dev(s),

thanks for this wonderful extension. I would like to suggest an additional feature. Usually, I set the panel on the vertical left with a size of 48. However, if I put many favorite apps on the panel, some of them became hidden on the screen. Please, see attached an example. It would be very nice if we can scroll over the panel to see the very end apps.  

Thanks in advance,

José Gadelha

![example](https://user-images.githubusercontent.com/38897885/83302558-f6425300-a1d1-11ea-9de6-d55e39d78afb.png)

**Comment by charlesg99** [comment]
Hello José! Thank you very much for pointing that out, this is something that should be working, but it seems like it hasn't for a long time on standalone panels (at least since v25). I added a fix for this to the branch I'm currently working on. Since you appear to already be using a Github version, could you please install the `feature-panel-positions` branch and see if that solves the issue on your end? Be aware that you might have to adjust the panel's item positions with that new branch. Thanks!

**Comment by gadass** [comment]
Whoa, that was really fast! 😄

I tested the branch @charlesg99 and everything's running fine now.
Thank you very much!

Best,

José Gadelha
