### ISSUE TITLE
Intellihide panel keeps going up again without being able to click or select something

### ISSUE THREAD

**Issue by ErwinBaeyens** [home-sweet-gnome/dash-to-panel#1159]
This  happens random and is gone when restarting;  that makes it difficult to run the extension alone. Also I run on wayland so the restart takes a lot of time 

**Describe the bug**
At random intervals it is impossible to make the panel drop down and select something.  What happens is that when pushing the mouse to the top of my screen the panel drops down and immediately goes back up.  It does that each time that I try to do that. 
It stops doing that when I switch to a different workspace and then back to the previous workspace.  

**Linux distribution and version**
***uname -a
Fedora 32 Linux  5.8.4-200.fc32.x86_64 #1 SMP Wed Aug 26 22:28:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

***output of cat /etc/*release*
Fedora release 32 (Thirty Two)
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 32 (Thirty Two)
Fedora release 32 (Thirty Two)
cpe:/o:fedoraproject:fedora:32

**GNOME Shell version**
Run `gnome-shell --version` from the command line to get this
GNOME Shell 3.36.5

**Dash-to-Panel version**
This can be seen in the Dash-to-Panel Settings in the About tab.
version 39

**Where was Dash-to-Panel installed from?**
The GNOME extensions websitec.

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**
I'm running on a dell precision m4800

See the image for the hardware specs
![gnomeabout](https://user-images.githubusercontent.com/15808295/92099382-b6939480-edda-11ea-8491-31d9d0a7bd49.png)

I have a 2nd machine that is nearly the identical except for the processor which is  a dual core I7-4600  that runs fedora 31 and X-org where I do not see this behaviour.

**Comment by siorenai** [comment]
**Intellihide panel _appears and hides_ in loops and unresponsive after exiting a Youtube video on Fullscreen Mode on Firefox, exclusively while a Firefox window is the active maximized window.**

I was about to submit this as a new issue. I suspect our issues are related, because the problematic behavior seems similar.
The problem occurs only with Dash-to-Panel extension enabled, stops after a gnome-shell restart and re-occurs on a new gnome-shell session after certain conditions are met.
Running `journalctl /usr/bin/gnome-shell -f -o cat &` command, while the glitch is happening, produces this output:

>  Window manager warning: WM_TRANSIENT_FOR window 0x4e01323 for 0x4e013e9 window override-redirect is an override-redirect window and this is not correct according to the standard, so we'll fallback to the first non-override-redirect window 0x4e00007.
Called enable_unredirect_for_display while unredirection is enabled.
clutter_input_device_ungrab: assertion 'CLUTTER_IS_INPUT_DEVICE (device)' failed
JS WARNING: [/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/update.js 52]: reference to undefined property "settings"
JS ERROR: TypeError: Me.settings is undefined
checkForUpdate@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/update.js:52:9
init/<@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/update.js:40:50
JS ERROR: TypeError: Me.settings is undefined
checkForUpdate@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/update.js:52:9
init/<@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/update.js:40:50
JS ERROR: TypeError: Me.settings is undefined
checkForUpdate@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/update.js:52:9
init/<@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/update.js:40:50
JS ERROR: TypeError: Me.settings is undefined
checkForUpdate@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/update.js:52:9
init/<@/usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/update.js:40:50
An active wireless connection, in infrastructure mode, involves no access point?
Removing a network device that was not added
**clutter_input_device_ungrab: assertion 'CLUTTER_IS_INPUT_DEVICE (device)' failed
clutter_input_device_ungrab: assertion 'CLUTTER_IS_INPUT_DEVICE (device)' failed**
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6600007
../mutter/clutter/clutter/clutter-actor.c:10556: The clutter_actor_set_allocation() function can only be called from within the implementation of the ClutterActor::allocate() virtual function.

**Describe the bug**
With the Intellihide option enabled for the Dash-to-Panel extension, on a gnome-shell X-org (X11) session, after a little while (few minutes usually) of playing videos on Fullscreen, on Youtube, on Firefox, immediately after exiting the Fullscreen, the Intellihide starts glitching _only_ whenever Firefox is the active, maximized window. If Firefox is not the active window or is minimized, the glitching does not occur and Intellihide behaves and reacts as it is supposed to. If Intellihide option is then disabled, the glitch doesn't exist and the panel behaves the same way on all kinds of application windows. 

The glitching looks like this: On a maximized Firefox window, approaching the hidden panel with the mouse brings the panel up (panel appears) and immediately afterwards, without moving the mouse at all, the panel is brought down (panel disappears) and it can get stuck at this loop of appearing-disappearing-reappearing-redisappearing indefinitely **or** it can do two loops of appearing-disappear and then not appear up again (all while the mouse is steady in a position that should be bringing and holding the panel up) **or** it can never appear in the first place even if it is being prompted by the mouse. This behavior makes the panel unresponsive to clicks and unusable on an active Firefox window. 

The selection between those three behaviors seems random to me or depends on minuscule differences in the pixel-position of the mouse and changes whenever the Firefox window is minimized and maximized again (for example if the panel doesn't appear at all, then minimizing and maximizing the Firefox window again will make the panel start doing some of the types of loops I described).

**Linux distribution and version**
Manjaro 20.1 kernel 5.4.60-2-MANJARO

**GNOME Shell version**
3.36.5

**Dash-to-Panel version**
38 (cc75702aea067394cb2dd23269942f09df4989b4)

**Where was Dash-to-Panel installed from?**
Pre-installed with the distribution (built-in)

**Screenshots / Video captures**
I might add a video capture at a later point.

**Additional Info**
HP Notebook - 15-bw009nv
If I should provide more info, please direct me.

Thank you.

**Comment by ErwinBaeyens** [comment]
That seems to be the same as what I am experiencing.  with your post  I realize that the problem can be related to the use of Firefox  in full screen.

**Comment by arfejes** [comment]
This is not unique to firefox I have the same issue with chromium as well. The only difference is that I do not need to open fullscreen video or anything, whenever chromium is in focus it is broken.

**Describe the bug**
I have two screens dash-to-panel is configured so I have the panel on both screens. Whenever a chromium window is in focus and I try to open the panel by touching the bottom edge of any of the two screens with the mouse pointer the panel appears as it should (appear delay is working)  but then disappears immediately.

**Linux distribution and version**
Manjaro 20.2 Nibia 5.9.11-3-MANJARO

**GNOME Shell version**
3.38.1

**Dash-to-Panel version**
40

**Where was Dash-to-Panel installed from?**
Pre-installed with the distribution (built-in)

**Additional Info**
Running on random PC with Ryzen 5 1600AF in B450m board + rx580

**Comment by charlesg99** [comment]
Hello, I can't reproduce this with the information you provided. For me Firefox and Chrome don't affect intellihide. Thanks!
