### ISSUE TITLE
Point status menu arrow up when panel is on bottom

### ISSUE THREAD

**Issue by jbicha** [home-sweet-gnome/dash-to-panel#116]
When the panel is on the bottom, I think it would be better if the system status menu arrow would point up instead of down because the menu opens up.

(I am talking about the little triangle at the far right of the panel.)

**Comment by franglais125** [comment]
Hi, I prepared a patch for this if interested: [388c767a9f92f9c80c0e83fe3be53c8c148d8146]

**Comment by jderose9** [comment]
@franglais125 Since there are arrows added by other items on the panel, I think this needs to be done in a generic way. For instance, the appMenu (when button is displayed on the panel) has an arrow, and so does the Applications menu extension.

If you look in panelStyle.js, the code is kind of confusing, but it already recurses through the left/center/right boxes and can run a provided function if the actor matches a provided comparison. And if a new actor is added to the panel it will run the comparison against them too. So you could look for arrows inside of PanelButtons and switch them there. Thank you!

**Comment by franglais125** [comment]
Ah, of course. This issue mentions the one in the corner, but other objects will add their own arrows, and it would make sense to flip them all... I'll try and look into it tomorrow. Cheers

**Comment by charlesg99** [comment]
This was included in the recent vertical changes that are now on master. Thanks!
