### ISSUE TITLE
Feature request: Folders

### ISSUE THREAD

**Issue by matteoformenti** [home-sweet-gnome/dash-to-panel#117]
Any thought about folders in the panel?

**Comment by dziku1337** [comment]
Could you please explain what the folders are? I have no clue.

**Comment by matteoformenti** [comment]
I'm sorry, you're right, my request is incomplete, here's an example:
In some android launchers, there's the option to create folders in older to group multiple programs, like in this picture http://www.androidpolice.com/wp-content/uploads/2016/04/nexus2cee_folders-728x488.jpg.
I was thinking about adding such a feature that allows users to group programs in folders in the dock and show all the icons in a "modal" after a click.
Just like adding gnome dash folders in the panel.
If that's not clear enough I could make a mockup!

**Comment by dziku1337** [comment]
I understand now. I have two design ideas for this:

![window folder concepts](https://cloud.githubusercontent.com/assets/11319008/24832540/7922e346-1cb2-11e7-9a60-c1cad0e99499.png)

The first concept is basically what you suggested. The downside is that you won't be able to display window previews. I mean, where would you position the panel with thumbnails? Imagine that you want to click on a thumbnail of the app in the middle of the green grid - Since the thumbnail list won't be directly above the icon, as soon as you move your mouse to the thumbnail list and leave the icon, there's high chance that the list will disappear. I mean, it will be very complicated.

The second concept will do much better. Upon clicking on the folder icon, the folder expands on the taskbar. This will allow displaying the thumbnail previews. The one bad thing that I can think of is that it could make some problems for narrow screens - opening one large folder or few smaller ones might lead to some complicaitons.

**Comment by matteoformenti** [comment]
What about the second concept but with just the running programs shown in the panel (the others stay in the modal along with the "launch a new instance" of the opened ones)

**Comment by dziku1337** [comment]
Showing the modal and the icons of running programs in the panel upon the click should be separate things because if you try to see the previews of one of the running programs, the modal will get in the way.

Another difficult thing is how to create, modify and remove folders. It's not something that already exists in gnome that we could utilize, all gnome can offer is to mark a program as favourite which adds it to Dash. I guess implementing the feature will take a lot of time.

**Comment by V3XATI0N** [comment]
seems like showing window previews would be made trivial by arranging the "folder" as a horizontal row rather than a square grid pattern.

**Comment by matteoformenti** [comment]
Actually GNOME Dash supports folders, but in order to modify them, an external program is needed

**Comment by jderose9** [comment]
@matteoformenti Do you mean the folders in the applications list?

**Comment by matteoformenti** [comment]
Yeah, that folders

**Comment by jderose9** [comment]
@matteoformenti Those folders can't currently be favorited so can't be added to the dash. (The dash in Gnome is the left side favorites bar in the activities overview). There's also no UI element to popup a folder contents. So those things need to be implemented as part of this feature.

Does it make sense to only allow favoriting/pinning or do they need to be a separately maintained type of folder? I believe each application can exist in only one folder currently. And, I'm not sure if you put an application in a folder for the taskbar that you necessarily want it to appear in a folder in that folder in the full applications list. It seems like these folders may need to be separately maintained.

**Comment by matteoformenti** [comment]
I'm sorry, I can't understand your question, I think that a folder should just be used to house the icons of the programs that I use frequently, divided by groups (IDEs, media, Internet), when I run one of this programs, the icon should pop out of the folder and stay in the taskbar. They should be independent of the unity folders since they are only grouped when not running.

**Comment by jderose9** [comment]
@matteoformenti I was trying to figure out whether the folders configured through Gnome Software could be re-used for this purpose or if the folders pinned to the taskbar would need to be maintained separately.

**Comment by jderose9** [comment]
@matteoformenti This is the type of folder I am referring to. I am assuming you wouldn't want to re-use these since each application can only belong to one folder and because you may not want all of the applications in one of these folders to appear in the taskbar folder?

![capture](https://cloud.githubusercontent.com/assets/2118702/24878312/a01aa0e8-1e00-11e7-9541-c3bd05fbf23a.PNG)

**Comment by matteoformenti** [comment]
I don't think those folders could be useful since as I said before, I suggest to only show closed programs in the folder. Imagine I have Videos, Visual Studio Code and weather in the folder, when I run Videos, it should disappear from the folder and appear on the taskbar as a standard program, when I then close it, it should disappear from the taskbar and reappear on the folder. Another option is to always show them in the folder, but when an already opened program is clicked in the folder, a new instance should be started. What do you think? Do you need any other mockup?

**Comment by dziku1337** [comment]
> Another option is to always show them in the folder, but when an already opened program is clicked in the folder, a new instance should be started.

This would be the easiest. The only two things that would need to be implemented are favouriting app folders in Show Applications and displaying their contents upon clicking them in the dash to panel. 

I don't know anything about extensions in Gnome Shell but how deep can we modify Gnome? Can extensions modify Show Applications? Can they modify implementations of some classes? I looked over the Gnome Shell source code and found implementations of both app-folder icons and regular app icons along with the logic for favouriting and unfavouriting. All of this can be found in ` js/ui/appDisplay.js` and `js/ui/appFavorites.js` files.

**Comment by jderose9** [comment]
@dziku1337 You can't stop code from running that already ran before the extension was enabled (obviously) and you have to return everything to it's previous state when you disable the extension, but you can pretty much replace any behavior in the gnome shell js code. Sometimes doing so requires pulling in/altering a rather large piece of shell functionality which increases the likelihood of breakage in a future version or conflicting with another extension, though.

**Comment by danielyzli** [comment]
> I understand now. I have two design ideas for this:
> 
> ![window folder concepts](https://cloud.githubusercontent.com/assets/11319008/24832540/7922e346-1cb2-11e7-9a60-c1cad0e99499.png)
> 
> The first concept is basically what you suggested. The downside is that you won't be able to display window previews. I mean, where would you position the panel with thumbnails? Imagine that you want to click on a thumbnail of the app in the middle of the green grid - Since the thumbnail list won't be directly above the icon, as soon as you move your mouse to the thumbnail list and leave the icon, there's high chance that the list will disappear. I mean, it will be very complicated.
> 
> The second concept will do much better. Upon clicking on the folder icon, the folder expands on the taskbar. This will allow displaying the thumbnail previews. The one bad thing that I can think of is that it could make some problems for narrow screens - opening one large folder or few smaller ones might lead to some complicaitons. I don't know, is this kind of folders going to come in handy?

I believe Mac OS X has supported this for a long time, and it's really useful; in OS X, you can expand as a list, as a grid, or 'fan out' animation.
