### ISSUE TITLE
Lock screen panel height should not change

### ISSUE THREAD

**Issue by ariflukito** [home-sweet-gnome/dash-to-panel#121]
Hi, this a cosmetic issue but I notice the lock screen panel height is the same as dash-to-panel panel height. But if I hover my mouse on the icons, the height will return to normal.

![virtualbox_arch linux_10_04_2017_16_45_59](https://cloud.githubusercontent.com/assets/5508660/24849125/9b641e14-1e0d-11e7-8edd-f389972f5a3c.png)

**Comment by jderose9** [comment]
@ariflukito I haven't seen this personally. Which distro/gnome version/display manager are you on?

Gnome disables extensions when locking and re-enables them on unlock. So, the panel should go back to the default shorter height. Perhaps you are receiving an exception during the disable. I would recommend to check the logs by opening a terminal and typing:

`journalctl /usr/bin/gnome-shell -f -o cat`

Then, lock the screen and unlock, and see if any errors have appeared in your terminal.

You should disable all other extensions first to rule them out as a contributor and also because they can make quite a bit of noise in the log.

Thanks!

**Comment by ariflukito** [comment]
@jderose9 I'm using GNOME 3.22.2 on Arch Linux and GDM display manager.

The only output I got after locking unlocking is this

`_cogl_buffer_fini: assertion '!(buffer->flags & COGL_BUFFER_FLAG_MAPPED)' failed`

No other extensions active.

**Comment by jderose9** [comment]
I tried antergos with GDM and still can't figure out how to reproduce, unfortunately.

**Comment by ariflukito** [comment]
I should have stated that I'm running on Virtualbox. I tried on Fedora on Virtualbox as well and it had the same problem.

**Comment by ariflukito** [comment]
@jderose9 It looks like it only happen if the panel position is at the bottom. If I put it on the top it doesn't have the same problem.

**Comment by ariflukito** [comment]
I'm going to close this issue since I cannot reproduce it anymore.

**Comment by jderose9** [comment]
I'm glad at least that it is working for you now! Thanks for reporting back.

**Comment by jderose9** [comment]
Hmm I've started seeing this myself. It only appears to happen when the screen locks due to inactivity, not when I lock it manually.

**Comment by ariflukito** [comment]
Yes I still experienced this from time to time but since I disabled
automatic lock it hasn't occured to me.
