### ISSUE TITLE
Panel Autohide malfunctions when Chromium engine browsers are maximized

### ISSUE THREAD

**Issue by genericusername3** [home-sweet-gnome/dash-to-panel#1237]
Whenever I maximize a Chromium browser window (I've tested Brave and Chromium so far) on one of my Manjaro setups, the panel hides and reveals itself when moving the cursor to the edge the panel is on (as expected). However, after the animation is finished, the panel promptly hides itself again. If it helps identify the problem, Dash to Dock has the same problem.

**Comment by genericusername3** [comment]
Feel free to ask for any information you need about my system, I feel this may not be sufficient.

**Comment by cylonrob** [comment]
I think I have the same issue with a newly installed Manjaro. The auto hide makes the panel flicker on and off over the maximized google-chrome browser.

**Comment by genericusername3** [comment]
> I think I have the same issue with a newly installed Manjaro. The auto hide makes the panel flicker on and off over the maximized google-chrome browser.
> 
> edit: The issue seams to be there when a) intellihide is NOT set to show while in full screen mode, but the chrome internal option is set to not use a system title bar, or b) when intellihide is set to show while in full screen mode and chrome is full screen. Haven't noticed other programs doing the same....maybe it's a chromium bug.

You're right, it definitely has something to do with Chromium's "Use system title bar and borders" setting — the problem does go away when disabling that. However, I've tried enabling "Allow the panel to be revealed while in fullscreen mode" and that did not fix the problem.

**Comment by guoxiao** [comment]
I reported the same issue in the comment of #1218

**Comment by arfejes** [comment]
It seems like firefox might be affected as well #1159

**Comment by charlesg99** [comment]
Working correctly for me, with and without "Use system title bar and borders" enabled.

**Things to do first**
- Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- Search existing opened and closed issues to see if the problem has already been reported.

**Linux distribution and version**
Ubuntu 18.04, Fedora 31, Manjaro 19.02, Arch, Debian 10.3, openSUSE Leap 15.1, etc.

**GNOME Shell version**
Run `gnome-shell --version` from the command line to get this

**Dash-to-Panel version**
This can be seen in the Dash-to-Panel Settings in the About tab.

**Where was Dash-to-Panel installed from?**
The GNOME extensions website, GNOME Software store, your distribution's package manager, pre-installed with the distribution, directly from github, etc.

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**

**Comment by itsyoshio** [comment]
I have this Problem still, albeit only when `Use system title bar and borders` in Chrome is UNTICKED
#1218 

**Linux distribution and version**
Manjaro

**GNOME Shell version**
GNOME Shell 3.38.2

**Dash-to-Panel version**
version 40 (53f941f90887135312ac7f4316a15c166f5216f4)

**Where was Dash-to-Panel installed from?**
pacman (but same issue with extensions.gnome.org)

**Screenshots / Video captures**
Now it gets interesting!

This is the View from Gnome ScreenRecorder (CTRL + SHIFT + ALT + R)


https://user-images.githubusercontent.com/12760988/103461933-2763a280-4d22-11eb-8a6f-74c799e069f7.mp4



looks good, right?

This is what i actually see (recorded with my Phone)


https://user-images.githubusercontent.com/12760988/103461949-39dddc00-4d22-11eb-9398-c438ef80f2ee.mp4

Scary…

**Comment by yarglory** [comment]
The same problem when used wayland!

Fedora 33, GNOME Shell 3.38.2, Dash-to-Panel version 40

**Comment by dekiakbar** [comment]
same problem happened to me, My system requirement :
Google chrome : Version 88.0.4324.150 (Official Build) (64-bit)
Dash to Dock panel : version 40
DE: GNOME Shell 3.38.3
OS : Arch Linux
Kernel : x86_64 Linux 5.10.15-arch1-1

**Comment by jnk5y** [comment]
**Linux distribution and version**
Fedora 34

**GNOME Shell version**
GNOME Shell 40.1

**Dash-to-Panel version**
version 40

**Where was Dash-to-Panel installed from?**
directly from github - make install

**Additional Info**
Same as folks above. 
- I have 2 monitors - `Use system title bar and borders` in Chrome is **UNTICKED** 
  - Chrome browser is **maximized** and the window in focus - the panel on the monitor **without** Chrome works fine
  - Chrome browser is **maximized** and the window in focus - the panel on the monitor **with** Chrome doesn't work (pops up for a millisecond and then is gone)
  - If Chrome is maximized and not the window in focus the panel works fine on both monitors

**Comment by sushanth-krishnaswamy** [comment]
It seems to work correctly in firefox for me. Chrome still has the issue though.

Firefox version: 91.0.2
Chrome version: 92.0.4515.159 (Official Build)
Gnome version: 3.38.5
Ubuntu version: 21.04

**Comment by vallabhtiwari** [comment]
Brave Browser shows the same issue. Chrome also
Ubuntu version: 21.04
It worked fine in Ubuntu 20.04
After I updated today this issue came.

**Comment by Commenter25** [comment]
Issue still exists, with both Firefox and Chrome. Functions just like jnk5y described. If the browser is maximized and in focus, attempting to open the auto-hidden panel will cause it to flicker in and out. Anything that causes it to animate will make it reappear during the animation, but once it is static it will be drawn over.

Firefox 103.0.1, Chrome 104.0.5112.79, Fedora 36, GNOME 42.3, Dash to Panel 50 installed from the extensions website. 

This issue seems to exist in [Fly-Pie](https://github.com/Schneegans/Fly-Pie) and [Panel Corners](https://github.com/aunetx/panel-corners) as well. Fly-Pie will similarly only appear when animating. Panel Corners will appear and disappear at the same time as Fly-Pie or Dash to Panel. This leads me to believe it's actually an issue with either GNOME or the browsers. However, I wouldn't have a clue what could be causing it and where I would report it. I'm reporting it here because a pre-existing unresolved issue exists, and hopefully someone will have a better idea than me about this.

**Comment by george-n-young** [comment]
Issue definitely still exists.

**Comment by all-iver** [comment]
Same here, I just upgraded from Ubuntu 20.04 to 22.04, and it was working before but now auto-hide is unusable with Firefox.

**Comment by thinh105** [comment]
I just upgraded from Ubuntu 20.04 to 22.04, and it was working before but now auto-hide is unusable with Chrome, but works OK with Firefox.

**Comment by acarlton** [comment]
This seems to be my issue as well, on Ubuntu 22.10 and was also happening on 22.04 (using Wayland). I have my dock permanently visible and Brave / Chrome windows seem to expand to full-screen width "underneath" it, in that I can see my left-most browser tab under the dock overlay and to be able to click on it, I need to resize the window and re-maximize it. Additionally, it seems to happen usually after the screen is turned off due to inactivity.

How does this issue get re-activated and removed from the 'stale' tag?

**Comment by jirimum** [comment]
Fedora 37
Gnome 43.2
Dash to panel 52

The issue still exists with Wayland and not with X11 and also when the program is maximized like Firefox
