### ISSUE TITLE
Repeated "Can't update stage views actor * is on because it needs an allocation." warnings

### ISSUE THREAD

**Issue by ftostevin** [home-sweet-gnome/dash-to-panel#1242]
Opening or closing windows with the taskbar visible causes multiple warnings of the above type:
```
Can't update stage views actor dashtopanelScrollview is on because it needs an allocation.
Can't update stage views actor StBoxLayout is on because it needs an allocation.
Can't update stage views actor Gjs_ui_dash_DashItemContainer is on because it needs an allocation.
Can't update stage views actor Gjs_dash-to-panel_jderose9_github_com_utils_DashToPanel_TaskbarAppIcon is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StBoxLayout is on because it needs an allocation.
Can't update stage views actor StLabel is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor ClutterText is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
Can't update stage views actor StWidget is on because it needs an allocation.
```
Doesn't happen when the taskbar is not displayed or when applications are grouped and a new window for an existing application is opened.  

Related gnome shell issue: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3098

**Linux distribution and version**
Arch

**GNOME Shell version**
3.38.2

**Dash-to-Panel version**
faf2ca26

**Comment by GaVenga** [comment]
Confirmed on Gnome Manjaro

**Comment by dantob** [comment]
its followed by this
`JS ERROR: TypeError: iconTexture.get_names is not a function
                                               _getIconPixBuf@/home/daniel/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:832:61
                                               _getColorPalette@/home/daniel/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/utils.js:851:27
                                               _getFocusHighlightColor@/home/daniel/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:1015:31
                                               _setIconStyle@/home/daniel/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:549:39
                                               _displayProperIndicator@/home/daniel/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:642:14
                                               _showDots/<@/home/daniel/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/appIcons.js:441:22
`

**Comment by Yionnara** [comment]
same bug on Debian

**Comment by charlesg99** [comment]
Hello, this is now fixed on the master branch, thanks!

**Comment by Spurlos** [comment]
Any ETA on when the fixed version would be published on extensions.gnome.org?

**Comment by MostHated** [comment]
I am getting these messages as well, using the most current version from GitHub on Pop_OS 20.10.

**Comment by Razer0123** [comment]
Getting the same

**Comment by malkhas** [comment]
Getting the same on fedora 34.

Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor ClutterClone is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor StIcon is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor ClutterClone is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor StIcon is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor ClutterClone is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor StIcon is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Jul 20 15:38:34 fedora gnome-shell[3167]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Jul 20 15:38:36 fedora avahi-daemon[920]: Withdrawing address record for fdb9:6caf:4b68:1:ed2:28fb:26c7:9c86 on ens33.
Jul 20 15:38:38 fedora systemd[1]: fprintd.service: Deactivated successfully.
Jul 20 15:38:38 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=fprintd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 20 15:38:40 fedora systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
Jul 20 15:38:40 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'

**Comment by amithiel** [comment]
same here, on Arch with gnome 40.3

**Comment by eiis1000** [comment]
Getting the issue with Pop on Gnome 3.38.4, specifically `Aug  7 16:55:29 pop-os gnome-shell[2637]: message repeated 51 times: [ Can't update stage views actor StWidget is on because it needs an allocation.]`

**Comment by funder7** [comment]
Found also on Ubuntu 21.04 and gnome 3.38.5

**Comment by robotard** [comment]
This issue appears to be getting closed through each route I'm trying to follow to a resolution... Gnome session restarts as far as logs go, but we still have a full desktop session still running,... Most painfully, it causes audio stutter both from Pulse and Pipewire... It also interferes with other processes generally, such as  downloads, scanning over wifi etc (session closed).X

This effects both 11 & Wayland, and I had it both on my old Intel i7, as well as my current Zenbook (Ryzen + NVidia)... 

Please stop closing the issue...

**Comment by Hyphaed** [comment]
PopOS 22.04 :: Still same error

Apr 30 12:30:18 pop-os gnome-shell[1592]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5654bd6e4340] is on because it needs an allocation.
Apr 30 12:30:18 pop-os gnome-shell[1592]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5654bec8b300] is on because it needs an allocation.
Apr 30 12:30:18 pop-os gnome-shell[1592]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5654bec8edd0] is on because it needs an allocation.
Apr 30 12:30:18 pop-os gnome-shell[1592]: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x5654bd6e4340] is on because it needs an allocation.
Apr 30 12:30:18 pop-os gnome-shell[1592]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5654bec8b300] is on because it needs an allocation.
Apr 30 12:30:18 pop-os gnome-shell[1592]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5654bec8edd0] is on because it needs an allocation.

**Comment by charlesg99** [comment]
@Hyphaed This happens here too as soon as I resize some windows (vscode, chromium), with or without dash to panel. See https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4281

**Comment by LinUwUxCat** [comment]
Hello, I have the same issue here, Pop!_OS 22.04, `journalctl /usr/bin/gnome-shell` is filled of this:
```
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x555cc39fa320] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x555cc6547700] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x555cc654b4a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x555cc6546740] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x555cc654a6a0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x555cc6546b30] is on because it needs an allocation.
```
![image](https://user-images.githubusercontent.com/46047705/168156951-9baf73ba-e68d-4899-9dee-7b703eeb79ec.png)
![image](https://user-images.githubusercontent.com/46047705/168157673-33fb7d95-ebe6-46a5-9cee-b0fdeb1c1095.png)

**Comment by tyleraharrison** [comment]
Why is this closed? Still having this issue

**Comment by antonio-emilio** [comment]
Still having this issue.

**Comment by oviniciusfeitosa** [comment]
Still having this issue too.

**Comment by nightwolfz** [comment]
same here

**Comment by isgursoy** [comment]
ubuntu 24.04, still there.

**Comment by pgmtags** [comment]
**The same problem.** (_Debian Trixie_). The window control panel is not displayed

```
Jul 18 04:03:24 AndrijZyn gnome-shell[3716]: Can't update stage views actor <panelBox>[<StBoxLayout>:0x56184b8c0b70] is on because it needs an allocation.
Jul 18 04:03:24 AndrijZyn gnome-shell[3716]: Can't update stage views actor <topbar-blurred-background-parent>[<StWidget>:0x56184f251550] is on because it needs an allocation.
Jul 18 04:03:24 AndrijZyn gnome-shell[3716]: Can't update stage views actor <unnamed>[<MetaBackgroundActor>:0x56184f7f7190] is on because it needs an allocation.
```

![зображення](https://github.com/user-attachments/assets/b912a0ef-91e8-4582-b418-6a201ea1f53f)

**Comment by pgmtags** [comment]
This behaviour is characteristic of pure Gnome on a stable release of Debian without extensions, I notice on different devices (laptop, desktop)

**Comment by tekeuange23** [comment]
On gnome 46.0, I turned off blur-my-shell and the journal stopped been spammed with that error message. Journal files size were literally eating my hard-drive space.

**Comment by byrevx** [comment]
Ubuntu 24.04 :

2025-02-03T20:37:20.800922+02:00 Legion gnome-shell[4256]: Can't update stage views actor unnamed [MetaWindowActorX11] is on because it needs an allocation.

**Comment by charlesg99** [comment]
> 2025-02-03T20:37:20.800922+02:00 Legion gnome-shell[4256]: Can't update stage views actor unnamed [MetaWindowActorX11] is on because it needs an allocation.

Known [gnome-shell bug](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4281) ignored since version 40

**Comment by liamquin** [comment]
> On gnome 46.0, I turned off blur-my-shell and the journal stopped been spammed with that error message. Journal files size were literally eating my hard-drive space.

You can trim the logs with journalctl --vacuum-size=30G (say), and edit /etc/systemd/journald.conf to make it remember that.

Having said that, i see these messages too...

**Comment by SimonDedman** [comment]
## This bug still exists on GNOME 49 / v72 — and it causes a severe memory leak

After ~48 hours uptime with dash-to-panel v72 on GNOME Shell 49.0 (Ubuntu, Wayland, kernel 6.17), gnome-shell consumed **10.4 GB RSS + 16.6 GB swap ≈ 27 GB total** on a 30 GB system.

### Evidence

**20,329 journal entries this boot**, firing continuously at ~10 ms intervals since boot second 11:

```
Can't update stage views actor unnamed [Gjs_ui_panel_WorkspaceDot] is on because it needs an allocation.
```

**Memory from `/proc/<pid>/smaps_rollup`:**

```
Rss:            10567984 kB
Pss_Anon:       10428120 kB   ← nearly all anonymous heap
Swap:           16726480 kB
```

### Root cause analysis

1. `panel.js:251–254` overrides the GNOME Shell panel's `vfunc_allocate` with `_mainPanelAllocate` (line 897), which only calls `this.panel.set_allocation(box)` — **bypassing child allocation entirely**.

2. The panel's children (activities button → WorkspaceIndicators → WorkspaceDot actors) remain in the Clutter stage graph but never receive allocations from the panel.

3. Although DTP sets `activities.container.visible = false` (default in `panelPositions.js:44`, applied at `panel.js:560`), the WorkspaceDot actors still trigger Clutter stage-view update checks on every repaint cycle.

4. `panelManager.js:182–194` overrides `vfunc_get_preferred_width` on the **WorkspaceDot class prototype** (via `Object.getPrototypeOf`), affecting all instances — including any WorkspaceDots used in the overview.

5. Each failed allocation check in the Clutter repaint loop creates GJS objects that accumulate faster than GC collects them, causing steady memory growth (~5 GB/day).

### Possible fix directions

- Ensure WorkspaceDot actors are properly unmapped/removed from the stage when the activities button is hidden
- Have `_mainPanelAllocate` also allocate the panel's original children (even to zero-size boxes) so Clutter's stage-view requirements are satisfied
- Explicitly destroy or remove the WorkspaceIndicators child actors when DTP takes over panel layout
