### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by mcanepa** [home-sweet-gnome/dash-to-panel#1319]
**Describe the bug**
After the lastest update, the extension is no longer working

**Linux distribution and version**
Debian 9.13

**GNOME Shell version**
3.22.3

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by janpieper** [comment]
I have the same problem since updating the extension...

![Screenshot from 2021-05-04 19-51-10](https://user-images.githubusercontent.com/426371/117047416-24011780-ad12-11eb-971a-f5b9e5e60499.png)

**Describe the bug**
Everything looks like before installing this extension.

**Linux distribution and version**
Ubuntu 20.04 LTS

**GNOME Shell version**
3.36.7

**Where was Dash-to-Panel installed from?**
https://extensions.gnome.org/local/

**Comment by janpieper** [comment]
Restarted my GNOME shell and it works again, but the extension settings now show me `version: 9999` :thinking: 

![Screenshot from 2021-05-04 20-30-36](https://user-images.githubusercontent.com/426371/117052090-9c1e0c00-ad17-11eb-82e1-31eb6ec1fc1c.png)

**Comment by jderose9** [comment]
Thanks @mcanepa ! I added some fixes in commit 1e46333210a8ed7a61d4c28e86f98f4abe579fcc. I will release a new version soon.

**Comment by tarun47m** [comment]
to restart press `Alt+F2` then `r`

**Comment by stsourlidakis** [comment]
I restarted GNOME with `killall -3 gnome-shell` and the extension works again.

**Comment by mcanepa** [comment]
@jderose9 Thank you!!! I'm now using v42 and everything works great
