### ISSUE TITLE
Icons fall down when animate hovering apps and autohide panel

### ISSUE THREAD

**Issue by ClimbMunchkin** [home-sweet-gnome/dash-to-panel#1363]
Trable: Sometimes icons fall down, this trouble happens when animate hovering apps and autohide panel
![fall_icons](https://user-images.githubusercontent.com/50596889/122342169-b7f30f80-cf5d-11eb-9815-2d8422b5b2c6.jpg)

solution:
to avoid this bug, please make a delay between panel auto-display and animate hovering icons

**Comment by ClimbMunchkin** [comment]
![fall_icons](https://user-images.githubusercontent.com/50596889/122342248-d822ce80-cf5d-11eb-952f-4e039908e2b9.jpg)

**Comment by Trainraider** [comment]
I also have this exact issue running dash-to-panel version 42 1e46333210a8ed7a61d4c28e86f98f4abe579fcc
Its inconsistent, and it's more situations than just when the icons pop up from Panel Intellihide and animate (Animate hovering app icons) before fully popped up. Whenever the icons are in motion up or down due to Intellihide, the icon animation can halt that motion, and start animating the icons relative to whatever location they were at at the start of the animation. So it's also possible to "catch" the icons by causing them to animate as the panel is in the process of hiding, which also can place icons in invalid positions. So another armchair solution I think might work is throughout the icons animation, its position in the animation should be relative to the correct un-animated default position of the icon, not the position the icon happened to be in when animation began. This way "Animate hovering app icons", and Panel Intellihide could both have simultaneous influence over icon position.
![dash-to-panel-falling-icons](https://user-images.githubusercontent.com/32771828/122854867-5b3b8000-d2e2-11eb-9836-00d8e10ccedb.jpg)

**Comment by meliodas1107** [comment]
I think it takes the hidden position as a reference and then increases its height from there . Im not really sure how it works but I also had this same issue . I would love to try to solve this too But im not sure where to look for it in code .
