### ISSUE TITLE
Setting window won't do anything if you open it via dash to panel

### ISSUE THREAD

**Issue by BehdadEs** [home-sweet-gnome/dash-to-panel#1365]
**Describe the bug**
If you right click on dash to panel and open dash to panel setting from there, setting window won't do anything when you click on something and it even't do not close when you click on X button, (I had to logout and login again to make it go away) but opening dash to panel setting with Gnome Extension app works just fine! 

**Linux distribution and version**
Fedora 34

**GNOME Shell version**
Gnome 40.1.0 Wayland

**Dash-to-Panel version**
Gnome 3.40 Version (9999)

**Where was Dash-to-Panel installed from?**
github

**Comment by jderose9** [comment]
I've found this generally happens when you open two or more instances of the settings window. I think you can't open two instances via the GNOME extensions app. I'm not sure whether we can detect whether one is open within the panel, but I assume we could do it however the GNOME extensions app does it.
