### ISSUE TITLE
[Feature Request] Add Super+Shift+# shortcut to open additional instance of application

### ISSUE THREAD

**Issue by DDriggs00** [home-sweet-gnome/dash-to-panel#1388]
In windows and (I think) KDE, when you press Super+Shift+1, it opens a new instance of the first application in the panel, rather than focusing or minimizing an existing instance. Would it be possible to replicate this behavior?

**Comment by Vinno97** [comment]
I think it'd be a good idea to make the htokeys for those actions configurable. 

In the meanwhile you can manually change this behaviour via the dconf editor:
In `/org/gnome/shell/extensions/dash-to-panel/` there are `app-ctrl-hotkey-[0-9]` and `app-ctrl-hotkey-[0-9]` keys with values that contain the actual hotkeys that trigger the actions.  Changing `['<Ctrl><Super>1']` to `['<Shift><Super>1']` for `app-ctrl-hotkey-1` and conversely changing `['<Shift><Super>1']` to `['<Ctrl><Super>1']` for `app-shift-hotkey-1`  should switch these keys around. 

It's a bit of a hassle, but you could do this for all keys if you'd want this functionality right now.

**Comment by DDriggs00** [comment]
Bump to prevent Auto-Close

**Comment by DDriggs00** [comment]
I think this issue still exists, and should not be auto-closed.

**Comment by charlesg99** [comment]
Hello, the hotkeys modifiers were not working properly since gnome 40. It should now work on the master branch. 

In gnome, pressing control and clicking an application launches a new instance, so the hotkeys do the same at all time (e.g. ctrl+super+1) launches a new instance of the first favorite, the same as a ctrl+click would.

On our end, the hotkeys use the same actions as the click+modifiers do, so if you configure the shift+click action to launch a new instance, the shift+hotkey should have the same effect (as in KDE).

![image](https://user-images.githubusercontent.com/33044886/162544409-eb476866-e753-45fc-ace8-e7f8fdbfe47d.png)

Hope that helps!
