### ISSUE TITLE
Launch via number feature with Super + number doesnt work correctly in gnome 40

### ISSUE THREAD

**Issue by iacobucci** [home-sweet-gnome/dash-to-panel#1397]
I installed Dash to Panel via extensions.gnome.org, and my beloved feature "launch via number" does't work correctly. As soon i have installed it it did work, but after fiddling with the configuration it shows unexpected behaviour: 
Super+number behaves like if just pressing the number while pressing just a number behaves like pressing the combination Super + number.
I have reinstalled the extension but still this annoying thing is happening. Can someone help me with this?

**Comment by rob32** [comment]
exact same issue here (fedora 34 wayland). 

- Today it stopped working with "Super+ Number"
- Now after toggle the feature on, only "Number" change focus.

This Feature was one big reasons why im still using GNOME.

**Comment by GinGin3203** [comment]
Fedora 34

The issue is also present for me. Conflicting with some package updates probably?

**Comment by GinGin3203** [comment]
Okay, I've found a way to fix it. @pattex16 @rob32 if you haven't solved the issue by yourselves yet, you might be interested

I've removed the Dash to Dock extension which installed from Fedora repos and reset settings for Dash-to-Dock and Dash-to-Panel in the `dconf`. This worked for me.

**Comment by Ashpan** [comment]
@GinGin3203 I don't think that worked for me. I performed the following steps
1. `sudo dnf remove gnome-shell-extension-dash-to-dock`
2. `sudo dconf reset -f /org/gnome/shell/extensions/dash-to-dock/`
3. `sudo dconf reset -f /org/gnome/shell/extensions/dash-to-panel/`

But to no avail. If there is anything I did wrong please let me know.

**Comment by GinGin3203** [comment]
@Ashpan I believe I also removed and installed again Dash-to-Panel... Sorry, my bad!

Also, I forgot to mention that I had Cinnamon installed, with Super+<num> keybindings enabled for the tray plugin (applet? whatever), and I reset settings for `/org/cinnamon` in dconf. I didn't mention it because at the moment I didn't think there could be any connection (my bad...). Not implying there _is_ a connecton, but if you also have Cinnamon installed it's worth giving a shot

To be honest, I just thought about anything that could interfere with Super+<num> keybindings and removed it and I was like "lol it worked". So if you have dock apps or DEs with Super+<num> hotkey defined, maybe try resetting them in dconf or removing them

**Comment by Ashpan** [comment]
Ah gotcha, I just a hard reset of all my gnome extensions and settings and when I reinstalled dash2panel, it fixed all my issues. Thanks so much @GinGin3203 !

**Comment by pattex16** [comment]
> Okay, I've found a way to fix it. @pattex16 @rob32 if you haven't solved the issue by yourselves yet, you might be interested
> 
> I've removed the Dash to Dock extension which installed from Fedora repos and reset settings for Dash-to-Dock and Dash-to-Panel in the `dconf`. This worked for me.

It worked for me too, thank you

**Comment by GinGin3203** [comment]
I'm glad to help :)

**Comment by skontar** [comment]
I had the same issue for the second time. Always happens after package update, but I am unsure which package. 

dconf settings get populated with some garbage, like keys for activating applications being '1', '2' etc. It is not exactly easy to get rid of it. You can remove the extension and then use dconf-editor to delete all setting keys, but only one by one. However, you can do `dconf dump /org/gnome/shell/extensions/dash-to-panel/ > dash-to-panel.dconf` to save your current settings and then it should be possible to load those settings. I will try it out next time.

**Comment by steve-todorov** [comment]
Not stale - just not fixed yet. :)

**Comment by steve-todorov** [comment]
@jenschurchill unfortunately your fix doesn't seem to work for me on Gnome 42 - pressing super + 1,2,3 starts up applications instead of switching workspaces. I had to re-apply my code changes from [above](https://github.com/home-sweet-gnome/dash-to-panel/issues/1397#issuecomment-937388684) :(

**Comment by steve-todorov** [comment]
@charlesg99 I'm sorry, but the bug seems to be re-appearing again. This ticket has not been resolved. In my current settings I have the `Hotkeys` disabled, but pressing Win Key + 1,2,3 (which has been configured for workspace 1,2,3) triggers opening the applications at index 0,1,2 (i.e. chrome, firefox, terminal, etc). 

![image](https://user-images.githubusercontent.com/2303663/162589797-ddc71c63-2d3c-46b5-a823-0885dc6eefcf.png)

The only way I fix this is by manually patching the `overview.js` file and have `return;` at the very beginning of `_enableHotKeys` and `_disableHotKeys`.

**Comment by charlesg99** [comment]
When the extension hotkeys are disabled, the gnome-shell one are active. With the extension hotkeys enabled, you should see a number on your appicon:

![image](https://user-images.githubusercontent.com/33044886/162590226-f198e76d-a1fa-4409-befc-18d76b14af14.png)


Otherwise it must be the gnome-shell one, which you can customize in dconf (org/gnome/shell/keybindings/switch-to-application-n):

![image](https://user-images.githubusercontent.com/33044886/162590197-78cb4152-f36b-497a-817a-a0acf2a2dc9f.png)

**Comment by githubuser402** [comment]
Love this feature, sometimes it worked will, sometimes some keys didn't work. Got to the setting and reset all hotkey to default, then everything started to work fine
