### ISSUE TITLE
main panel switches to monitor 2 when using multiple monitor inputs

### ISSUE THREAD

**Issue by Lukens4242** [home-sweet-gnome/dash-to-panel#1405]
**Describe the bug**
I have a 3 monitor setup.  Monitor 3 is often switched to a different input for another computer, and then switched back.  I have the DtP setting for "display the main panel on" set to Primary Monitor.  When I change the input on monitor 3 to display my other computer, this setting gets reset to "second monitor" and then I have to change it back to primary.  When I change the input on monitor 3 back to be the linux machine, the "display the main panel on" setting gets reset to "second monitor" again, and I have to switch it back to the primary monitor.

**Linux distribution and version**
Fedora 34

**GNOME Shell version**
40.3

**Dash-to-Panel version**
43

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by OlegKrikun** [comment]
Have the similar problem =(

In my 3-monitor setup, the panel position randomly changes after every reboot (instead of "Primary Monitor").

**Linux distribution and version**
Arch

**GNOME Shell version**
40.3.0

**Dash-to-Panel version**
43

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

P.S.: I use Wayland

**Comment by kaimast** [comment]
I think I am still seeing this.

**Comment by Lukens4242** [comment]
I too am still experiencing this.

**Comment by OlegKrikun** [comment]
Have this issue every reboot =(
