### ISSUE TITLE
Need to restar Dash-to-Panel to make Overview work

### ISSUE THREAD

**Issue by vantu5z** [home-sweet-gnome/dash-to-panel#1409]
After system boot Overview does not work (does not show windows, only grey background).
If Dash-to-Panel is restarted (disable - enable in Extensions app) than Overview works as expected.

Gnome-shell 40.3 (Xorg)
Dash-to-Panel (43 and git master version)

**Comment by renbus** [comment]
I think I have the same issue, but, for me at least, it seems to be a problem with Dash-to-Panel, Dash-to-Dock and the Gnome Overview screen. I just can't have the three of them working altogether.

In the Extension window, if I turn off all the extensions, the Overview works fine.
If I turn on Dash-to-Panel only, favorites icons in the Overview disappear.
If I turn off Dash-to-Panel, and turn Dash-to-Dock on, everything works, but Dash-to-Panel is off.
If I turn on both Dash-to-Panel and Dash-to-Dock,  the Dock disappear (both in Overview or normal mode).
If I turn off Dash-to-Dock again and only keep Dash-to-Panel turned on, then I get favorites icons in the Overview, but no Windows or Workspaces, just a grey background!

Looking at journalctl, there is a lot errors happening:

Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: Can't update stage views actor Gjs_ui_workspace_Workspace is on because it needs an allocation.
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: Can't update stage views actor StIcon is on because it needs an allocation.
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: Can't update stage views actor StIcon is on because it needs an allocation.
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: Can't update stage views actor Gjs_ui_windowPreview_WindowPreview is on because it needs an allocation.
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: Can't update stage views actor StIcon is on because it needs an allocation.
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: Can't update stage views actor ClutterActor is on because it needs an allocation.
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: _st_create_shadow_pipeline_from_actor: assertion 'clutter_actor_has_allocation (actor)' failed
Jul 29 14:50:17 Renaud-ThinkPad-T430 gnome-shell[824]: clutter_actor_allocate: assertion '!isnan (real_allocation.x1) && !isnan (real_allocation.x2) && !isnan (real_allocation.y1) && !isnan (real_allocation.y2)' failed

These lines appeared in the log when I pressed the Super key to launch the Overview, while having Dash-to-Panel and Dash-to-Dock but turned on. These errors are repeated many times.

Gnome-shell 40.3
Dash-to-Panel 43

I am also using Manjaro. Note that this problem happen only since Manjaro fully updated to Gnome 4.

**Comment by vantu5z** [comment]
Turn off `Dash-to-Dock` extension and seems `Dash-to-Panel` works fine without it.
For now use `Dash-to-Plank` instead of `Dash-to-Dock`.
