### ISSUE TITLE
Files icon click-action minimize not working (Ubuntu 21.10 Impish)

### ISSUE THREAD

**Issue by rmkimathi** [home-sweet-gnome/dash-to-panel#1456]
**Describe the bug**
Clicking on the files icon opens a new instance. Other icons click-action minimize ok. Also files icon lacks a preview

**Linux distribution and version**
Ubuntu 21.10 (Impish Indri)

**GNOME Shell version**
gnome-shell version 40.2-1ubuntu6

**Windowing System**
X11

**Dash-to-Panel version**
D-to-P version 43

**Where was Dash-to-Panel installed from?**
directly from github

**Comment by vsxed** [comment]
Same happens on Wayland (Default in Ubuntu 21.10 (Impish Indri)).

If i disable and instantly re-enable the extension (so that the unity bar shows up for a second) the error does not happen. 

Seems like it only appears if no nautilus window is open at D2P's Startup. After closing all of them, the bug re-appears.
Whats also weird: after closing all "6 windows" via the context menu, the windows will be closed, but the context menu shows still "Quit 6 Windows", like it was not updated at all.

https://user-images.githubusercontent.com/1070998/135599262-b72bf5cd-d402-48c3-97e2-69f95d1a41e8.mp4

**Comment by rmkimathi** [comment]
Patience can be painful. We shall wait for the fix.

**Comment by diegolagoglez** [comment]
Yes, it works. I could add the Files button to the panel using Arc Menu. Thank you very much.

But Files icon still doesn't expand the button when Files windows are open, as you can see in the attached screenshot.

![Files icon doesn't expand the button](https://user-images.githubusercontent.com/2563312/137920254-aa1850ce-16c3-4c15-a598-de6a19182959.png)

**Comment by mrwebfr** [comment]
This solution works for me. 
```
dconf reset -f /org/gnome/shell/extensions/dash-to-panel/
gsettings set org.gnome.shell.extensions.dash-to-dock isolate-locations false
```
`Alt+F2` and `r` or logout and login

**Comment by charlesg99** [comment]
Dash to dock issue.
