### ISSUE TITLE
Extension not usable/working after installation from git

### ISSUE THREAD

**Issue by dfev77** [home-sweet-gnome/dash-to-panel#1474]
I've installed the extension from git per instructions in https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation
After install (and reboot), nothing is shown, when trying to configure it, Tweaks complains there is an issue with the extension and gives the below error as details.

Using Ubuntu 20.04.2

> Error: Invalid parameter interfaces (element 0 was not a GType)
> 
> Stack trace:
>   _init/GObject.Object._classInit@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:448:27
>   registerClass@resource:///org/gnome/gjs/modules/core/overrides/GObject.js:94:22
>   @/home/florin/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/prefs.js:2286:30
>   _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
>   OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
>   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
>   run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
>   main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
>   run@resource:///org/gnome/gjs/modules/script/package.js:222:19
>   start@resource:///org/gnome/gjs/modules/script/package.js:206:5
>   @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
>

**Comment by Knowledge-Wisdom-Understanding** [comment]
Facing the same problem in the latest debian kali linux 2021.3

The first thing I tried was making sure all packages for gnome were up to date.

```shell
sudo apt autoremove
sudo apt update
sudo apt upgrade -y
```
This still didn't resolve the problem so after a little google-fu I found this article which had the incorrect file path
https://githubmemory.com/repo/home-sweet-gnome/dash-to-panel/issues/1429

I found this article much more helpful.
https://www.pragmaticlinux.com/2021/06/manually-install-a-gnome-shell-extension-from-a-zip-file/

 Also, I didn't need to install the browser extension so you can skip that most likely.
Already had all the apt packages required installed on my system.

# Steps to Fix.

1. Download the correct version of dash-to-panel for the version of your gnome-shell
```shell
❯ gnome-shell --version
GNOME Shell 3.38.6
```

![image](https://user-images.githubusercontent.com/36655901/139509746-4b4d4505-187f-4189-82b0-53e47aa7714e.png)
![image](https://user-images.githubusercontent.com/36655901/139509806-32d3cefd-57fc-4b7c-87ad-9e88d183dded.png)
![image](https://user-images.githubusercontent.com/36655901/139509841-86e09da7-940c-4c1a-b828-904028a8f244.png)

2. Place the file in your machine wide gnome-shell extensions location, not in ~/.local/share/gnome-shell/extensions/ but instead in `/usr/shared/gnome-shell/extensions`

```shell
cd /usr/share/gnome-shell/extensions
mkdir dash-to-panel@jderose9.github.com
mv ~/Downloads/dash-to-peneljderose9.github.com.v42.shell-extension.zip dash-to-panel@jderose9.github.com/dash-to-peneljderose9.github.com.v42.shell-extension.zip
cd dash-to-panel@jderose9.github.com
unzip dash-to-peneljderose9.github.com.v42.shell-extension.zip
rm dash-to-peneljderose9.github.com.v42.shell-extension.zip
busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting…")'
```

The final magic command i used that seemed to fix it was

```shell
busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting…")'
```

I didn't have much luck with the gnome-extensions command.

and now when i re-open the extensions GUI i see

![image](https://user-images.githubusercontent.com/36655901/139511581-08f7fef7-b461-405b-be4c-d30754db45fb.png)

Not really the greatest fix since it's not the same kali dash to dock i'm used to but it works i guess.

haven't rebooted my system yet but maybe that will magically restore the old dock 🤷‍♂️ 😅

**Comment by oliver-wahome** [comment]
I had a similar issue but after a lot of googling I managed to find a solution:

1. First install the "GNOME shell integration" to your chrome browser.

2. Once installed click on the "GNOME shell integration" extension in chrome. It should take you to "extensions.gnome.org"

3. Once there search for "dash-to-dock" extension by michelle_g. Click on it and install the extension to your computer.

4. When its done installing, the favorites bar should appear. To verify that the extension has been installed go to the extensions application on your OS and under manually installed you should find the newly installed Dash to Dock extension.
