### ISSUE TITLE
Show Application did not show any applications.

### ISSUE THREAD

**Issue by VNGamerGit** [home-sweet-gnome/dash-to-panel#1478]
**Describe the bug**
What I meant in the title is: the Show Application menu didn't show any application icons. Strangely, if you search any applications using the search bar, the searched application will come up.

**Linux distribution and version**
Ubuntu 21.10 (beta)

**GNOME Shell version**
GNOME Shell 40.5

**Dash-to-Panel version**
43.

**Where was Dash-to-Panel installed from?**
From GNOME Extensions website.

**Comment by VNGamerGit** [comment]
> Same problem here with Ubuntu Impish Indri just a black screen , Applications only show if you search for them.

Maybe cause it's just beta? It's just a few days or weeks before the official release of Ubuntu 21.10 though, so...

**Comment by jlemonde** [comment]
> Maybe cause it's just beta? It's just a few days or weeks before the official release of Ubuntu 21.10 though, so...

I doubt because it is only one week left until final release. UI freeze was one month ago, and from today the release candidate came out, which means that nothing is planned to change any more, unless there is a dramatic issue popping up.

Furthermore, this bug only happens if dash-to-panel is enabled, otherwise it works fine.

**Comment by eightninezero** [comment]
This bug also occurred in Arch (GNOME 40.5). A few days ago it worked very well though.

**Comment by zhboner** [comment]
https://github.com/home-sweet-gnome/dash-to-panel/issues/1437#issuecomment-902875910 solves this issue on Ubuntu 21.10
