### ISSUE TITLE
Show Applications doesn't

### ISSUE THREAD

**Issue by Draco18s** [home-sweet-gnome/dash-to-panel#1551]
**Things to do first**
#1492 looked similar, but marked as resolved.

**Describe the bug**
When clicking the "show applications" task bar icon, the screen flashes with the desktop image, then vanishes. It is as if the menu attempted to open and then was immediately closed before it could be populated.

Pressing Super shows a completely different menu (same functionality, but appearing as a modal instead of screen overlay).

**Linux distribution and version**
Ubuntu 21.10

**GNOME Shell version**
Gnome 40.5

**Dash-to-Panel version**
9999

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![show-applications](https://user-images.githubusercontent.com/1750680/148794551-f2b275dd-1ab5-4d13-ba1d-7827bece512f.gif)

**Comment by oyylumo** [comment]
i started having this after i updated pop_os to 21.10

**Comment by HeyHouBenjo** [comment]
Same problem here on Pop!_OS 21.10

**Comment by charlesg99** [comment]
Are you planning on switching to 22.04? I honestly don't think I'll look into gnome-shell 40 issues, but concentrate on the ones on LTS releases, as well as the newest gnome-shell versions.

**Comment by Draco18s** [comment]
I don't know when Pop will switch to 22.04, I just had the system check for updates and it says its current.
Noted, however.

**Comment by Draco18s** [comment]
Pop dropped 22.04 in the last 24 hours (got the notification this morning) and just finished whacking my gnome extensions into shape (there's always one that upon updating it throws an error and I have to fuss around with older versions by hand until I find one that does work).

This issue is still present.

I _think_ what Dash to Panel is doing is showing (or trying to show) is all workspaces (Super+D) rather than showing all applications (Super+A)
#1645 may be a duplicate.

**Comment by charlesg99** [comment]
Ha sorry, in your original post you said it was on Ubuntu (which is true in a sense :wink:) so I missed it, but yes, PopOs does override the overview and basically makes it impossible to access the app grid, which is what's normally revealed by the show applications button of dash to panel (Super+A). 

I think it would be better to remove the show applications from the panel and use PopOs alternative in this case, it would be more in line with what PopOs intended and show their own apps menu:

![image](https://user-images.githubusercontent.com/33044886/165834438-897d4d0b-240f-4aec-880b-54059f314f16.png)

Otherwise if you want to use the default gnome-shell app grid that the dash to panel show applications reveals, you'll have to disable PopOs extensions that prevent it from appearing correctly:

![image](https://user-images.githubusercontent.com/33044886/165834947-fbbd65a8-074c-44dd-b0fe-8642b9c8dacd.png)

The rest of the panel seems to work fine for me, which is a surprise considering the amount of modification that PopOs puts on top of gnome-shell.

**Comment by Draco18s** [comment]
Pop does make some changes, yeah, but I honestly have no idea how much (and oops, my bad for not mentioning Pop originally, I usually try to do that!). I get the occasional weirdness in theme-related things, but 99% of the time it's functional, just not well styled. I've turned off those two cosmic things, we'll see if that fixes it (nothing yet after a shell restart, but might need to do a full system, which I'll do later).

**Comment by Draco18s** [comment]
Ah there we go. Things didn't actually get disabled right, had disable them again, do another logout login, and then catch one of them turning itself back on, turn that one off, and relog again and now things work the way I expect.
