### ISSUE TITLE
Some fullscreen windows get wrong position after suspend and resume

### ISSUE THREAD

**Issue by philippun1** [home-sweet-gnome/dash-to-panel#1600]
**Describe the bug**
Open two windows in fullscreen (i.e. firefox or gnome-builder) and suspend your machine. Open it again to resume. The window in the background will now have a wrong position, moved down (I assume by the size of the panel) behind the panel leaving a gap at the top (see screenshots). Does not happen with every application, i.e. gnome-terminal does not trigger it. Also does not happen every time, I assume the device has to be suspended for a little while.

**Linux distribution and version**
Ubuntu 22.04

**GNOME Shell version**
GNOME Shell 42.0

**Dash-to-Panel version**
master branch (15f9e0b072bcecb422e038d209425a5a0bf80c0c)

**Where was Dash-to-Panel installed from?**
directly from git

**Screenshots / Video captures**
![Screenshot from 2022-04-03 17-21-28](https://user-images.githubusercontent.com/57151725/161436676-17b9a312-6c35-409a-8bb1-52ff037d726c.png)
![Screenshot from 2022-04-03 17-23-16](https://user-images.githubusercontent.com/57151725/161436685-199d1299-f693-4f5c-8740-fbd7b94af0ce.png)

**Additional Info**
[dtp-log.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/8404929/dtp-log.txt)

**Comment by charlesg99** [comment]
I'm seeing something similar on GS 42, every time I restart gnome shell some of my windows move down. At first I thought that it was because of the vanilla GS top panel space or something, but it also happens on my secondary monitor or when the extension is disabled :shrug:. Also when the extension is first enabled with the system (resume, unlock), the windows aren't yet created, so I don't think we can do much or are the cause of the issue.

As a workaround we could wait for the initial windows to be created, check if they're maximized and "re-maximize" them, but my guess is that a mutter patch will solve this in the near future. Let's wait and see for a couple of weeks or so.

**Comment by erenoglu** [comment]
I can consistently reproduce this on Gnome 43.1 Wayland on up to date Arch. Dash-to-Panel at bottom or left, upon lock and unlock, any maximized windows will shift down by probably the size of "hidden" top panel. This makes Dash-to-Panel hard to use as each time I lock and unlock, I need to re-maximize my windows. The app windows also overlap the Dash-to-Panel's panel.
This shift for example prevent you from seeing the bottom or left side of the window as the Dash now overlaps that area

**Comment by kaimast** [comment]
For me: when I try to drag the window, it will fix its position.

**Comment by richardbowman** [comment]
I'm worried to find this bug having been marked stale and open so long. I love Dash to Panel but this is a major issue especially on my laptop where I tend to keep windows maximized. Any potential pathway to fixing? I can try to be helpful and offer testing support, debugging, etc.

**Comment by kaimast** [comment]
> I'm worried to find this bug having been marked stale and open so long. I love Dash to Panel but this is a major issue especially on my laptop where I tend to keep windows maximized. Any potential pathway to fixing? I can try to be helpful and offer testing support, debugging, etc.

The best path is probably to help fix the [mutter bug](https://gitlab.gnome.org/GNOME/mutter/-/issues/1627) first.

**Comment by kaimast** [comment]
I don't have this problem on GNOME 44 anymore, but now, after resuming, windows fill the entire screen, and the panel obscures parts of them.

**Comment by mcclure** [comment]
Since installing Ubuntu 23.10 and Dash to Panel on a laptop I am getting this bug on most resumes when the computer has been sleeping for an extended period and the frontmost window is maximized. I cannot make it happen on demand but I am seeing it very regularly, multiple times a day. De-maximizing and re-maximizing the window fixes the problem.
The amount of space the window moves down by looks to me like exactly the height of the "regular" panel which would otherrwise be at the top of the screen.
I run with 150% display scale.

Screenshots:

[<img width=260 src="https://github.com/home-sweet-gnome/dash-to-panel/assets/277318/57d13d39-1e40-400b-8ed8-e1005bccdb98">](https://github.com/home-sweet-gnome/dash-to-panel/assets/277318/57d13d39-1e40-400b-8ed8-e1005bccdb98) [<img width=260 src="https://github.com/home-sweet-gnome/dash-to-panel/assets/277318/24a772c5-8f6a-4ede-b3da-c60f1bd4f3b1">](https://github.com/home-sweet-gnome/dash-to-panel/assets/277318/24a772c5-8f6a-4ede-b3da-c60f1bd4f3b1)

Notice in the second screenshot that only the frontmost window was affected.

**Comment by Spinnekop** [comment]
Still happening on gnome 45 dtp 59 on arch.

**Comment by mcclure** [comment]
By the way I have done some testing with Xorg since I posted before and I *only* get this problem in Wayland. I don't know if I'm seeing the same bug as everyone else but I only see the bug when I log in a Wayland session, never Xorg.

**Comment by Spinnekop** [comment]
Wayland hey? Who woulda thinkit!!

**Comment by philippun1** [comment]
No longer happens on a fresh install of Ubuntu 23.10 (tested on wayland).
On another machine with Ubuntu 23.10 upgraded from 23.04 it still happens...

**Comment by Kurbo26** [comment]
I have a relatively fresh one-week-old Ubuntu 23.10 install (not an upgrade). I'm new at this so have not been doing a lot of tweaking. I have this issue when the panel is set to bottom. However, if I set the panel size to 32 (which seems to be the normal size of the top bar), the empty space at the top after resuming does not occur for me. If I set the panel size to something other than 32, then the issue is easily recreatable.

**Comment by City-busz** [comment]
I submitted a patch to mutter that fixes this problem:
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3601

**Comment by charlesg99** [comment]
Thanks @City-busz!

**Comment by AndreaCovelli** [comment]
> I submitted a patch to mutter that fixes this problem: [gitlab.gnome.org/GNOME/mutter/-/merge_requests/3601](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3601)

@City-busz Thanks very much! When do you think it will be available on ubuntu lts?

**Comment by City-busz** [comment]
Mutter version 46.0 and later contains this fix.

**Comment by sagebind** [comment]
Seeing as the latest Ubuntu LTS was just released, presumably the next LTS to include this would be 2026...

**Comment by philippun1** [comment]
@sagebind Ubuntu 24.04 contains mutter 46, which contains the fix.

**Comment by City-busz** [comment]
@chaserene Unfortunately it cannot be really fixed from a GNOME Shell extension. I recommend you to ask Debian maintainers to backport [this commit](https://gitlab.gnome.org/GNOME/mutter/-/commit/35335e65af75a58c8ca7f2bb3a325884155b34b1) to their mutter package.
