### ISSUE TITLE
Can't open system menus from the panel while I have a focused app on full screen when the panel is set on top.

### ISSUE THREAD

**Issue by agoogleuser** [home-sweet-gnome/dash-to-panel#1682]
**Describe the bug**
When I enter full screen on an app on multi monitor setup (mine was dual monitor with same resolution), while focusing on that app, I can't interact with the system menus on the panel such as date/time or applications menu on the other monitor.
### steps to reproduce:
- Set the panel on top.
- Open an app that has full-screen capabilities, like Firefox which I will use as an example here.
- On any monitor, Press F11 or open a video on YouTube for example to make it full-screen.
- Keep the app focused.
- Click the top panel system menus, such as Application menu or Date/Time or Quick settings menu. They simply don't interact.

**Linux distribution and version**
Ubuntu 22.04 LTS

**GNOME Shell version**
Gnome 42.0

**Dash-to-Panel version**
50

**Where was Dash-to-Panel installed from?**
Extensions manager app from Ubuntu store.

**Screenshots / Video captures**
Couldn't upload for some reason.

**Additional Info**
I like pizza.

**Comment by agoogleuser** [comment]
I forgot to mention that this is on multi-monitor setup, so it shouldn't be visible on the monitor my application is on full screen, but interacting with the panel on the other monitor has that issue I described in detail above, mine was one on the left and right with the same resolution, I couldn't take a recording at the moment.

**Comment by wagyourtail** [comment]
> I don't think I understand, when an app is in fullscreen the panel shouldn't be visible, unless you have intellihide enabled and allow it to be revealed that way. I've tried that and I can't reproduce the issue. Thanks!

I think I can reproduce this behavior with a little demo...

steps:
1. hit windows key to open arc menu, showing the panel despite the fullscreen content
2. try to click on something in the panel
3. observe as it hides instead of showing the submenu/doing the expected action

differences for my setup: only displaying the panel on my primary monitor

expected result: able to click stuff and have the panel stay focused while interacting with it and its sub elements

![Peek 2022-06-11 09-57](https://user-images.githubusercontent.com/6234704/173195396-d16a14db-d067-4b0f-9b6a-ebbf163d14b9.gif)

**Comment by charlesg99** [comment]
Still can't reproduce, try the latest version with dash to panel as the only enabled extension. We'll re open if needed
