### ISSUE TITLE
Cursor selection by search results in the overview does not work correctly when displaying the main panel not on primary monitor

### ISSUE THREAD

**Issue by d-enk** [home-sweet-gnome/dash-to-panel#1694]
**Linux distribution and version**
Ubuntu 22.04

**GNOME Shell version**
42.1

**Dash-to-Panel version**
v50

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
![image](https://user-images.githubusercontent.com/43112758/173049609-715edae7-776e-4809-9af8-d92d71382e6a.png)

![Untitled](https://user-images.githubusercontent.com/43112758/173066721-ea6a336d-d65e-4631-ae3c-b338ae03ee4d.png)

![video_2022-06-10_15-40-32](https://user-images.githubusercontent.com/43112758/173066658-4b086e80-adfa-48d0-b6f8-84213fbcc5fd.gif)

**Comment by LionHeartP** [comment]
I've been having this issue ever since the Gnome 42 update dropped. 
In previous versions, the applications would appear on the main monitor instead and there would be no issue selecting with the mouse.
So reverting this to show results on main monitor would probably fix it.
Ideally there would be an option to select which screen you want the search results to appear, because I liked that they used to show up on my primary monitor tbh.

**Comment by charlesg99** [comment]
Thanks for reporting this, it should now be fixed on the master branch
