### ISSUE TITLE
Panel keeps switching back to main instead of staying on secondary

### ISSUE THREAD

**Issue by ZetaDaemon** [home-sweet-gnome/dash-to-panel#1742]
**Describe the bug**
I want the panel to just stay on my secondary monitor and I am able to set it there but whenever my computer blanks out the screen it seems to switch back to the main monitor, and in the settings it also has it showing as set to main instead of keeping to monitor 2.

I can go into settings again and set it back to the secondary monitor but it does not stay that way.
However it seems to have no issues staying on the main monitor.

**Linux distribution and version**
Fedora 36

**GNOME Shell version**
42.4

**Dash-to-Panel version**
50

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Comment by ACH1980** [comment]
I have this in some other way... For me I have a 3-Screen-Setup (numbered 1-3-2 from left to right) with my primary screen in the middle (see attached Screenshot below), as panel screen. It does however switch to monitor 2 every time my screen was locked, which is weird because it switches from primary to another.

As in #1704 there is a user having similar problems switching to it's largest screen I have to mention that my screens are all the same specs (all 1920x1080@60Hz) tho they are different configurations (1: DP-HDMI 3: DP-DP 2: HDMI-HDMI) might be, that it priorizes there if the specs are the same. 
Also it seems like the problem of #1681 could be also related

![image](https://user-images.githubusercontent.com/39656381/190371279-8062c8ae-9746-4cfc-8820-96faa20b4e1d.png)

**Comment by charlesg99** [comment]
Fixed in v51
