### ISSUE TITLE
Opening system menu and calendar makes clicking application menu unresponsive

### ISSUE THREAD

**Issue by RickardLundberg** [home-sweet-gnome/dash-to-panel#1793]
Dashtopanel 52
Gnome 43 on Arch Linux, running wayland. 

Using Dashtopanel on the top of the screen. System menu and clock visible and to the right. The default application menu extension enabled and to the left on the panel. When opening system menu or calendar then hovering over to the application menu it does not open when hovering with the mouse and it is unresponsive and you cannot click it. Some of the taskbar is also unresponsive when clicking.

**Comment by charlesg99** [comment]
Hello, this by design in gnome-shell. The menu grabs all inputs until it is closed again (<kbd>ESC</kbd> or click). 

There is a dash to panel setting that changes the default gnome-shell behaviour as to how other menus on the panel open (makes it so you have to click to open another menu instead of hover), maybe that's what you're referring to?

![image](https://user-images.githubusercontent.com/33044886/207478930-c5f42844-836a-45df-8f7c-dd0ba1aa7978.png)

**Comment by RickardLundberg** [comment]
The issue seem to have been resolved with some update lately, cause the problem don´t happen anymore. I can now click on the menu and then hover over the panel and all items is responsive and open.
I've tried the activate panel menu button, when I had the problem, but it did not make any difference.
