### ISSUE TITLE
Custom Icon for Activities Button

### ISSUE THREAD

**Issue by blueray453** [home-sweet-gnome/dash-to-panel#1919]
The way "Show Application Button" has option to change icon and size, add an option to add icon and change size of the icon to "Activities Button".

**Comment by zleonov** [comment]
Just wanted to chime in that this is def. a much wanted feature. It makes total sense since we can customize the  _Show Applications_ button. This would be great because a lot of shell themes are awesome, other than their take on the activities button. And by default, dash-to-dock just inherits the activities button from the chosen shell theme.

This causes many inconsistencies. For example, the shell theme I am using specifically makes the activities button small and round. Even when I replaced the icon manually I still had to edit the stylesheet to get things semi-working.

**Comment by blueray453** [comment]
@skewty I currently use https://github.com/ahmafi/gnome-activities-workspace-name and https://github.com/tty2/horizontal-workspace-indicator

It looks like:

![Peek 2023-09-28 19-05](https://github.com/home-sweet-gnome/dash-to-panel/assets/855297/75b8f431-fde4-4f03-b0e2-349dec3af411)

I think Gnome 45 will have an experience similar to this.

If you're wondering, i change the workspace by scrolling over the task bar.

**Comment by skewty** [comment]
That'd be great if they didn't cease development with Gnome 45: "With gnome 45 the gnome community get a new awesome builtin workspace switcher. This extension does not have any reason to exist."

PS: I am running Gnome 45

**Comment by charlesg99** [comment]
duplicate of #1650
