### ISSUE TITLE
Esc in Application Menu leads to Window Overview

### ISSUE THREAD

**Issue by kamulos** [home-sweet-gnome/dash-to-panel#192]
Pressing Esc in the application menu does not go back to the desktop/window as expected, but first shows the window overview. A second esc press then returns to the starting point

**Comment by jderose9** [comment]
I felt this was a bit weird myself but it is how dash-to-dock behaves so I left that behavior. You could have possibly opened the app list from the overview, or even moved back and forth between them multiple times, and I wasn't sure which behavior should be taken (ESC would close if I opened the app list first? Or only if I had never visited the overview since opening the app list initially?)

Now that I am looking at it, while ESC goes to the overview, Super can be used to close the app menu.

Anyway, I'm curious to get some additional feedback here. Thanks!

**Comment by franglais125** [comment]
This is not only the behavior of dash-to-dock, but the shell itself.

If you use Super+A to open the application view, ESC will bring you to the overview, not back to where you started.

I guess what I'm trying to say is that this is not a problem with the extension, but with how the overview+application view behaves by design. I'm not sure what is better, but it's at least consistent.

**Comment by darekdeo** [comment]
Would it be possible to add checkbox for overriding this behavior?

The current behavior is default for the shell but I believe it is made this way in shell because user has to go through activities first to get to applications menu without using shortcuts. By default call to action is always like Activities -> Application Menu.

While using Dash-to-panel Activities and Application Menu feel more separated than in default shell. Because of that in my opinion going back to desktop by pressing Esc in application menu would feel more natural.

**Comment by jderose9** [comment]
@darekdeo So if this setting was toggled would ESC always close the full-screen mode even if the user started in the Activities Overview? Or would it track whether Activities Overview or Applications is opened first?

**Comment by darekdeo** [comment]
@jderose9 Good question,

I think it is not possible to swap between Activities Overview and Applications by clicking "Activities" button while being in Applications menu, the full-screen mode is being closed after clicking Activities even when Applications menu was displayed during click. Because of this Activities Overview and Applications menu should be treated like single program.

I know Gnome or desktop overall is not mobile system, but I think Android and its Intent system is good example how to handle this kind of situations. If gnome Activities (and App menu) would be an Android program then it would be treated this way (Assuming Esc is Back button):
Desktop -> Activities -> Applications -> Esc -> Activities -> Esc -> Desktop
Desktop -> Applications -> Esc -> Desktop
(of course in Android Intent to certain part of application needs be called from other application, not from desktop screen, but that's not case of this discussion)

Another reason why it should be preferred way to navigate back to Desktop with Esc is because of this current behavior (correct me if I am wrong, but I am sure this is also Dash to Dock behavior):
Desktop -> Applications -> *clicking second time applications menu icon* -> Desktop

**Comment by charlesg99** [comment]
Hello, an option to return to the desktop when pressing the escape key was added to the master branch. This seemed logical and doesn't impact existing gnome-shell behaviors, as it only applies when entering the overview by clicking the Show Application button. Thanks!
