### ISSUE TITLE
overview gnome dock appears after using lockscreen

### ISSUE THREAD

**Issue by howdev** [home-sweet-gnome/dash-to-panel#2202]
**Describe the bug**
After using lockscreen. lock and unlock. Open overview, gnome dock appears at the bottom also along with dash to panel. Disable/enable dashtopanel restores to normal.

**Linux distribution and version**
ubuntu 24.04 LTS

**GNOME Shell version**
GNOME 46 

**Dash-to-Panel version**
64

**Where was Dash-to-Panel installed from?**
Extension Manager 

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**
![Screenshot from 2024-10-19 23-59-14](https://github.com/user-attachments/assets/da86b65d-3f69-484f-ba94-679918ee23da)

**Comment by charlesg99** [comment]
Thanks!

**Comment by starball5** [comment]
Thanks for the fix. Is there a date I can expect this to release? I have version 64 right now, which I see was released ~30 days ago.

**Comment by r-o-i** [comment]
Thank you for fixing this! It was super-annoying, and not really your fault (I blame GNOME 46) 🥇

**Comment by v-marinkov** [comment]
@charlesg99 This problem seems to have reoccurred on Fedora 42 GNOMe 49 with Dash to Panel 72. Even if I disable the dash from Just Perfection, it reappears after every log off/reboot.

<img width="2560" height="1600" alt="Image" src="https://github.com/user-attachments/assets/e7f318ff-8c61-4e52-9549-d9a7ad49b506" />
