### ISSUE TITLE
Merge in window changing via mouse scroll from dash-to-dock

### ISSUE THREAD

**Issue by amittos** [home-sweet-gnome/dash-to-panel#30]
Hello. Thank you for this awesome extension. I love it. 

One of the most useful (imo) extensions out there is Scroll Panel (https://extensions.gnome.org/extension/1096/scroll-panel/). Unfortunately, it doesn't work with Dash to Panel. 

I kindly urge you to consider supporting it. Maybe adding the particular features to Dash to Dock? 

Thank you very much :)

**Comment by jderose9** [comment]
I installed Scroll Panel and it seems to work just fine with Dash-To-Panel. What issue are you seeing?

Dash-to-panel does remove the application's menu which Scroll Panel uses for switching an application's running instances, though that will optionally be added back with #29.

Are you looking for functionality being worked on here?
https://github.com/micheleg/dash-to-dock/pull/428

I'll be happy to merge it in when they are finished working on it. It's worth noting that the current scroll behavior is to scroll back and forth through the application icons when they don't all fit in the panel, so that functionality would be lost if the wheel is re-purposed.

Thanks!

**Comment by benfairless** [comment]
You could check out the solution I posted in #37 . Works as a great solution IMO

**Comment by jderose9** [comment]
So does this extension resolve this issue or is there some other change still needed?
https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/

**Comment by jocap** [comment]
Is there any chance that scrolling on a particular prorgam's icon to cycle its window (à la Dash to Dock) could be implemented? The Scroll Panel extension cycles through all windows, without considering to which program they belong.

**Comment by triorr** [comment]
Someone test this patch please:
https://pastebin.com/raw/RCUxvqVU

**Comment by AlexWayfer** [comment]
> So does this extension resolve this issue or is there some other change still needed?
https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/

Doesn't work when I scroll on icons. :worried:

**Comment by charlesg99** [comment]
Hello, this feature was added to master. Scrolling on an appIcon should now cycle through the corresponding application windows. Thanks!

**Comment by smellyonionman** [comment]
I really love this feature, for some reason it is more responsive than the menu buttons in-app, a lifesaver during heavy cpu load.  Could you allow us to bind upward and downward scroll differently?  (Using up to cycle and down to minimize would be quite nice.)
