### ISSUE TITLE
Dash to panel transparency doesn't work as expected

### ISSUE THREAD

**Issue by bilelmoussaoui** [home-sweet-gnome/dash-to-panel#306]
The transparency introduced on the latest gnome version doesn't work as expected with any shell theme, even the default one :(

As you can see here in the screenshot
![screenshot from 2017-12-23 15-09-44](https://user-images.githubusercontent.com/7660997/34320178-f5bbd7de-e7f3-11e7-9c61-ae3706d56b05.png)

The transparency works as expected with other themes. If i reduce the icon size to something like 24px; everything works correctly; so i'm guessing that this issue is due to some min-height property?

**Comment by jderose9** [comment]
Hmm.. It seems to be working fine for me, on Fedora 27 / 3.26.2. Which version are you on?

![screenshot from 2018-01-24 21-54-09](https://user-images.githubusercontent.com/2118702/35368439-5a5f230a-0151-11e8-83bb-489a0fa9f8d5.png)


@franglais125 - Have you seen this, by any chance?

**Comment by joca-bt** [comment]
Can't seem to find the option for it (version 11). Is that for the development version?

**Comment by jderose9** [comment]
It's just the new behavior of gnome 3.26+ with the default shell theme.

**Comment by franglais125** [comment]
@bil-elmoussaoui @jderose9 Sorry, I don't have much time these days to really look into this issue.

The fact that it can be fixed by reducing the icon size is suspicious. @bil-elmoussaoui would you mind posting a video/gif of the behavior?

The calculation of the geometry uses the actor height. Could it perhaps not be set properly when modifying the `min-height` property? It would be weird.

In `panel.js`:
```
let panelBottom = panelTop + this.actor.get_height();
```

**Comment by jderose9** [comment]
Is this still a problem?

**Comment by charlesg99** [comment]
Hello, the new opacity/color options added to master resolve this issue. Thanks!
