### ISSUE TITLE
show desktop button doesnt work with "extend panel menu" extension

### ISSUE THREAD

**Issue by shawn-dsilva** [home-sweet-gnome/dash-to-panel#309]
the show desktop button appears in the middle of the icons after a reboot,is fixed by turning off,then on the show desktop button toggle,i have to do this everytime i start up the computer though
are the dash to panel settings stored in a setting file somewhere? i could use a script to turn off/on the show desktop button everytime i  start the computer if  such a settings file exists

**Comment by jderose9** [comment]
I looked at the code for this extension. It adds the new panel elements at the rightmost position in the container only. We've avoided trying to fight with other extensions for position so that the two extensions don't end up in an endless cycle of repositioning.

We could potentially redesign the Show Desktop button so that it would look acceptable if it appears anywhere in the panel, but I think the best option would be for Extend Panel Menu to allow its position to be configured (similar to Top Icons Plus).
