### ISSUE TITLE
Workspace Indicator

### ISSUE THREAD

**Issue by spantaleev** [home-sweet-gnome/dash-to-panel#336]
It would be nice if this extension could have a "workspace indicator" feature, like the one in the [Window List](https://extensions.gnome.org/extension/602/window-list/) extension.

Installing a separate extension, like [Workspace Indicator](https://extensions.gnome.org/extension/21/workspace-indicator/) is an alternative. But the downside is that the indicator appears somewhere within the tray icons, which is not ideal.

In contrast, the workspace indicator integrated into the [Window List](https://extensions.gnome.org/extension/602/window-list/) extension always renders at the most-right corner of the bar, like this:

![window-list-workspace-indicator](https://user-images.githubusercontent.com/388669/35817958-76b939b4-0aa7-11e8-8295-69c1ff270d8d.png)

Due to Fitts’ Law, just like the "Show Desktop" button already part of dash-to-panel, such a most-right workspace indicator is very convenient to use.

If this is to be implemented, there'd be a natural conflict about whether the "show desktop" button or the "workspace indicator" should take over the screen's right corner. Perhaps only one of these features ought to be active at a given time (below I also discuss another possibility where both are active).

Beneficial features for a workspace indicator (in order of importance):
- always stays at the most-right corner (not `1px` to the left or something, as that would ruin usability)
- performs workspace-changing via mouse wheel scroll
- displays the current workspace (e.g. "2"). Optionally, the display label may be configurable to include how many workspaces are available (e.g. "2/4"). As some people have a Static number of workspaces, showing the "out of 4" part is useless and wastes horizontal space.
- might be clickable, which would bring up a menu for switching via mouse click (Workspace 1, Workspace 2, ..)

By default, this "workspace indicator" widget could be super-tiny, because:
- no aiming with the mouse is required (Fitts' corner)
- no clicking is required in most cases (scrolling with the wheel changes the workspace)
- indicating only the active workspace might be the default (e.g. "2") - this doesn't take much space

I can also imagine another "super-compact" mode, in which the workspace indicator does not even show the workspace number. In that case, it could be as tiny as the "Show Desktop" button is right now.

-------

Which makes me think of another idea: **merging the workspace indicator with the "Show Desktop" feature**.

Here's how it might work:
- both features could be active at the same time (and since workspaces are a frequently-used feature on Linux desktops, both features could be active by default)
- this new "Show Desktop & Workspace Indicator" button could be made a bit wider, so it could display the workspace number (e.g. "2") by default.
- Fitts' corner is already utilized, nothing to change and no fighting between features, because the same element is used for both "Show Desktop" and "Workspace Indicator"
- scrolling with the mouse wheel on top of the button changes the active workspace
- clicking on the button performs the "Show Desktop" action (like now)
- another idea: `Shift+Click`ing on the button brings up the drop-up menu for switching workspaces
- another idea: some kind of gesture like "click + drag up" might activate the drop-up menu -- although this might be unnatural to do in GNOME

**Comment by mweirauch** [comment]
I'd like to propose another way of doing it:
I am still using the [TaskBar extension](https://extensions.gnome.org/extension/584/taskbar/) but its support seems to fade a bit. Its setup to show windows (ungrouped) only - no favourites.

![taskbar](https://user-images.githubusercontent.com/1134031/47037089-4fd14780-d17e-11e8-9aa8-0cbad1b9523c.png)

It has a built-in workspace indicator which can be left- and right-clicked to cycle through the workspaces forward and backward accordingly. (The little "1" you see next to the show-desktop icon.) When I am lazy I am using this to switch workspaces instead of my `ALT+F[1,5]` combo. (A old BeOS legacy.)
The advantage of having the workspace indicator near the window icons is the small "travel distance" after cycling a workspace  - via mouse-click on the workspace indicator - to the application/window icon.

This way you don't have to come up with solutions for combining the show desktop control with a workspace indicator. (And as already mentioned, the "travel distance" would be way longer.)

(If you now also have a solution for integrating the "Places status indicator" I'd be more then happy :))

**Comment by spantaleev** [comment]
@mweirauch, travel distance is much longer when the workspace indicator is at the edge, but by utilizing the edge, it's much easier to hit.

Pushing your mouse diagonally as far as you wish will automatically make it stick to the edge (unless multiple monitors are involved.. in which case, aiming is probably required in any case)

**Comment by mweirauch** [comment]
@spantaleev I didn't mean the travel distance *to* the workspace indicator, but the travel distance *from* the workspace indicator (after having clicked it) to reach the application/window icons. (The dash entries.)

So what it boils down to (in case there's more interest in this feature):
* provide a workspace indicator
* to make it more usable - have it react in LMB/RMB clicks to cycle through workspaces (a dropdown like seen in other extensions is way too clumsy to use)
* have different placement options
  * left of application/window list (after application menu)
  * left of show-desktop control

**Comment by korelstar** [comment]
I like this idea very much. :+1: 

It's becoming more interesting, since other workspace indicator apps are not compatible with current Gnome versions and are not maintained anymore (e.g. [WorkspaceBar](https://extensions.gnome.org/extension/464/workspacebar/) or Workspace Bar), or they are too simple (e.g. [Workspace Indicator](https://extensions.gnome.org/extension/21/workspace-indicator/)). I'm looking forward to this feature! :tada:

**Comment by korelstar** [comment]
Please see #741 for a proof of concept implementation :smiley:
