### ISSUE TITLE
Show preview window on top of thumbnail?

### ISSUE THREAD

**Issue by orschiro** [home-sweet-gnome/dash-to-panel#375]
Hey @jderose9 love your extension and the way I can sneak preview windows! :-)

One suggestion, can previewed windows be displayed on top of the thumbnail windows?

Currently thumbnails overlay previews. 

Demo screencast: https://youtu.be/N7_Mbkx6PCY

Thanks!

**Comment by fthx** [comment]
Hi,

I experience the same "issue". I suggest that during preview, the thumbnail pop-up becomes transparent enough (maybe a setting could be welcome here) ?

**Comment by jderose9** [comment]
I don't think we can reasonably show the hovered window over top of the thumbnail windows as that would make it rather difficult to interact with the thumbnails.

I think the issue here is that the preview windows are quite large compared with your overall desktop real estate. There have recently been new features released to adjust the size of the window previews. Does adjusting your preview windows to a smaller size resolve this problem?

**Comment by charlesg99** [comment]
> I suggest that during preview, the thumbnail pop-up becomes transparent enough

That might work, although it would add moooore settings to the previews... @jderose9 what do you think?

**Comment by jderose9** [comment]
Personally, I think the new size and background opacity settings should cover it. I'm having trouble imagining the thumbnail itself being transparent and then being able to make sense of both the foreground and background images.
