### ISSUE TITLE
Numerical hotkeys does not work after login

### ISSUE THREAD

**Issue by alisabzevari** [home-sweet-gnome/dash-to-panel#397]
I use the ubuntu 18.04 with the default ubuntu. After any logout and login, the hotkeys doesn't work anymore. But when I go to extension settings and disable/enable hotkeys setting, it will start working.

I guess something in ubuntu desktop overrides the hotkey registration.

Any idea how to investigate more?

**Comment by alisabzevari** [comment]
Thanks for fast response and sorry for not enough information! Here are more information and some questions answered:

> do you mean going to the lock screen or really a user logout (or both)?

Both

>  Also, do you have any other extension that could use the same key combination?

No. It happened just after installing 18.04.

> Result of running `journalctl /usr/bin/gnome-shell -f -o cat`:

Actually, I see a lot here! These lines are suspicious:
* `Window manager warning: Trying to remove non-existent keybinding "app-hotkey-1".`
* `Window manager warning: Trying to re-add keybinding "app-hotkey-1".`
* `JS ERROR: ReferenceError: GLib is not defined
enable/<@/home/username/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:52:13`

And here is the whole log: 
[dash-to-panel-hotkey-problem.log](https://github.com/home-sweet-gnome/dash-to-panel/files/1971865/dash-to-panel-hotkey-problem.log)

**Comment by charlesg99** [comment]
Ha, I installed Ubuntu 18.04 and there are some setting name collisions between dash to panel and the default ubuntu dock hotkeys. It shouldn't be a problem since normally extensions remove their keybindings when they are disabled, but it seems that disabling the ubuntu dock doesn't complete successfully and leaves the keybindings active.

Could you please pull the "fix-hotkeys-collisions" branch and see if that solves the issue? The dash to panel setting names were modified to fix the issue. Thanks!

@jderose9 Do you see potential problems by fixing it that way?

**Comment by alisabzevari** [comment]
I tried the `fix-hotkeys-collisions` branch and worked :+1: 

I think having prefixes for hotkey names is a more robust fix because then the codebase doesn't have a ubuntu dock specific code in it. And maybe later you have to add another fix for collision to something else!

BTW, your reaction was fascinating. You are one of the best maintainers of open source projects that I've ever seen. :medal_military:

**Comment by charlesg99** [comment]
Great, glad it fixes it and thanks for the kind words. This is a piece of code that (I think) originated in dash-to-dock, so it is used in dash to panel as well as in ubuntu dock (hence the collision). I would also favor changing the setting names, but as @jderose9 pointed out, current users might loose customized shortcuts if we fix it that way. 

Unfortunately I don't see a way to only change the name provided to addKeyBinding() as it calls to C code right away and it expects the settings object, instead of the value to assign to keybinding. I also tried making sense of the extensions disable/enable order, without much success :) (both extensions are enabled/disabled multiple times when login in, go figure).

As for the name changes, we could include some code that would "migrate" the existing users shortcuts to the new keybinding names (and delete the old ones afterwards so it is only done once). This routine would need to be removed in the future (say, when v15 is released).

Any thoughts?

**Comment by alisabzevari** [comment]
:+1: for settings migration. If we can run such a routine right after installation that would be better.

**Comment by jderose9** [comment]
@charlesg99 Thanks for resolving this two different ways :) I didn't realize when writing my previous comment that the name passed was actually the setting name (which, then, seems odd that they would conflict if the namespace is different, but I'm not too familiar with how that stuff is being handled). Your new approach looks like a better way to handle disabling the Ubuntu dock, but if you think it makes sense to rename the keybindings after all (or still), I don't think it's the end of the world to lose existing hotkey settings on update. Thanks again!!

**Comment by charlesg99** [comment]
@jderose9 Yeah this is weird... you pass the setting name and the settings object to the addKeybinding function, then the corresponding value is read in C code from the settings object using the setting name... Not very flexible :)

I think the second solution is best since it makes sure that dash to panel is enabled after disabling the ubuntu-dock, in whatever order the extensionsystem feels like enabling them. This solves the hotkey collisions issue and should prevent other potential conflicts that could arise from sharing parts of the same code base. Thanks for your insight.

**Comment by alisabzevari** [comment]
Hi @charlesg99,

I've installed the new fix and it is working.

**Comment by charlesg99** [comment]
Great, thanks for the feedback. The fix has been merged to master.
