### ISSUE TITLE
Clicking on a peeked window should disable animation

### ISSUE THREAD

**Issue by ddnexus** [home-sweet-gnome/dash-to-panel#398]
When you are peeking a window, you have the workspace of that window displayed on full screen _in place_ of the current one. When you click on the peeked window (thumbnail).. the visualization of the peeked workspace disappear, the current workspace appear, and the peeked workspace arrive again with the usual animation.

In case of click on a peeked window, its workspace is already visualized and should simply "stay there" without anything else.

**Comment by charlesg99** [comment]
Hello, sorry a bit late to the party, but here goes! 

I'm currently working on the peek feature and I can't find a js way to switch between workspaces without the animation. What I propose is, upon entering peek, move to the workspace where the window is and dim the other windows on that workspace. Then, if you click on the thumbnail, you'll already be on that workspace, so no animation will occur. If you move the mouse out without selecting the thumbnail, you'll return to your current workspace. 

I think it would be less confusing as you would "see" what's going on, instead of thinking you magically switched workspaces when in fact you did not. Sounds reasonable?

@jderose9 what do you think?  

Thanks!

**Comment by ddnexus** [comment]
@charlesg99 That would probably work, hoping there is no drawback switching the workspace back and forth.

While you are at it: is there any way we could also choose to pull the peeked window to the _current_ workspace? That would be extremely useful!

**Comment by charlesg99** [comment]
The new window previews are available on a separate branch, if you'd like to try it. More info [here](https://github.com/home-sweet-gnome/dash-to-panel/issues/611#issuecomment-495455229).

I ended up entirely disabling the workspace switch animation, as it was just too much going on at the same time. I'm wondering how you would see the "pull the peeked window on the current workspace"? Do you mean that you'd like to drag the window preview out of its frame and that would bring it on the current workspace?

Thanks!

**Comment by ddnexus** [comment]
Thank you @charlesg99 
For the peeked window "Move to current Workspace". I meant a simple contextual menu or a button, or anything that will just move the window from its workspace to the current one. No drag required: just move it to the foremost layer of the current workspace, maintaining its position on the screen.

It should work exactly like the standard "Move to Workspace Up/Down/Left/Right". It should be "Move to current Workspace". It is actually a missing system feature IMO. Why the heck is not already there is beyond my understanding, but we could get it fixed at least withing the extension.

**Comment by ddnexus** [comment]
Should we open a new issue for this topic (that changed from the OP)?
