### ISSUE TITLE
[Bug] Dash to panel pollutes logs with "Invalid work id" error

### ISSUE THREAD

**Issue by MateusRodCosta** [home-sweet-gnome/dash-to-panel#461]
I can see the following error quite a couple of times on the gnome-shell logs:

```
Sep 15 18:29:55 delart gnome-shell[30337]: JS ERROR: Invalid work id 172: Error: Invalid work id 172
                                           queueDeferredWork@resource:///org/gnome/shell/ui/main.js:681:18
                                           _queueRedisplay@/home/mateusrc/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js:477:9
                                           wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                           _connectWorkspaceSignals/this._workspaceWindowRemovedId<@/home/mateusrc/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/taskbar.js:464:94
```

This happens with the latest version on Gnome Extension.

Running Arch Linux 64-bits.

gnome-shell version is 3.30.0+25+g179cd0a3c-1

**Comment by charlesg99** [comment]
Hey MateusRodCosta, thank you for this report! I can't seem to reproduce this on Arch with gnome-shell 3.28.2. Could you please see if you can spot a pattern when the error appears in the log? Using `journalctl /usr/bin/gnome-shell -f -o cat` should help with the monitoring. My guess would be that it happens when you log out and still have some windows open or something of this nature? Thanks!

**Comment by MateusRodCosta** [comment]
So, I had to do a hard shutdown of the system due to it running out of RAM earlier.

I'm currently unable to reproduce this again, I do remember it appearing basically when the panel hides and/or unhides due to Intellihide. I could be wrong though.

If I see it again happening I will update with more info.
