### ISSUE TITLE
Empty space in taskbar and centered position

### ISSUE THREAD

**Issue by abakkk** [home-sweet-gnome/dash-to-panel#470]
Hello,

There is an empty space at the end of the taskbar (in scrollview, after boxLayout):

![capture d ecran de 2018-09-27 23-07-51](https://user-images.githubusercontent.com/33428071/46175915-d7c5df00-c2ad-11e8-8d2b-2809a7b79378.png)

It visually makes the centering false when taskbar is centered:

![capture d ecran de 2018-09-27 23-09-00](https://user-images.githubusercontent.com/33428071/46176050-5e7abc00-c2ae-11e8-8491-141c3d20e9c9.png)

I don't find in the code where this empty space comes from.
Is it necessary ? If it is, can I add an offset (it seems equal to panel-size + appicon-margin ?) in the taskbar allocation when it is centered ?

**Comment by charlesg99** [comment]
Hey abakkk, I think this space is an intentional padding so when the taskbar is full it doesn't look to cramped next to the right hand side icons. Not sure if we should remove it. @jderose9 what do you think? I remember you mentioned it in #402.

If you want to change it locally, the width of this empty space is defined by the variable `let HFADE_WIDTH = 48;` in taskbar.js (line 56). Setting it to 0 should give you a perfectly centered taskbar. Thanks!

**Comment by jderose9** [comment]
@charlesg99 I have noticed the space before but haven't looked into it. I think it shows the faded icon in the scroll view when the available width is exceeded, showing the user that there is more to the right. But, I would assume that style could instead be applied to the edge of the taskbar area when there is more to scroll to, rather than allocating that extra space at all times.
