### ISSUE TITLE
super+(1-9) with multiple instances per application behaves not as expected when not grouped

### ISSUE THREAD

**Issue by voidray** [home-sweet-gnome/dash-to-panel#471]
dash-to-panel settings: don't group applications
Version: v16
Lets say I have nautilus, gedit and firefox as favorites. When I press super+1 nautilus opens and on super+2 gedit opens as expected. When I open an additional nautilus window super+2 doesn't focus gedit, but the second nautilus window. In would find it mouch more helpful if I could still use the numbers for the applications (muscle memory). This is also the behavior on Windows.

**Comment by charlesg99** [comment]
Hi voidray, I think that what you describe should be the default behavior (1 hotkey per application, same as when grouped), but I'm unsure if changing this now would affect people who got used to it. Also, I don't think adding a setting for this would be worthwhile. 

@jderose9 what do you think? For consistency sake, I would just correct it (without adding a setting) since this is clearly an undesired side effect of ungrouping applications. Thanks!

**Comment by jderose9** [comment]
I agree that changing the launch number as windows open is unintuitive. Since we respect the click action setting, users can set their click action to `Cycle windows` and rotate through them with the same hotkey if they wish. I think that it can be probably be changed without adding a new setting.

**Comment by charlesg99** [comment]
I'll modify this, do you think it's best to display the same overlay number on each instances of the same app in the taskbar? Or is it better to only display the number on the first instance of the app and have no overlay on the following ones? 

I think I would display the same number on each instances of the same app, what do you guys think?

**Comment by charlesg99** [comment]
I added the modification to master. I tried both options mentioned previously and ended up using the same overlay number for all instances as no overlay number looked confusing. Please let me know if this makes sense. Thanks!
