### ISSUE TITLE
Only available for a few distributions

### ISSUE THREAD

**Issue by damian101** [home-sweet-gnome/dash-to-panel#481]
At the moment this awesome GNOME Shell Extension is only available for most Debian based distros and Antergos (as it is also in the AUR it should also work on other Arch based distributions).
This makes me sad.

**Comment by fchiacchiaretta** [comment]
Maybe I don't get your point, but I think you're saying those distro _package_ this extension.
You can simply install from [GNOME Extensions website](https://extensions.gnome.org/extension/1160/dash-to-panel/), right?

**Comment by highvoltage** [comment]
Surely it's up to a distribution to package software for their system? Maybe you should file a bug with the distribution you're using instead.

**Comment by damian101** [comment]
"You can simply install from GNOME Extensions website, right?"
How?
How can I install it when it is not in a matching repository and there are no matching packages I can download?

**Comment by damian101** [comment]
> Surely it's up to a distribution to package software for their system? Maybe you should file a bug with the distribution you're using instead.

**Comment by jderose9** [comment]
@damian101 Install the package `chrome-gnome-shell` on your distro (even if you don't use chrome) if it isn't already, and then install the browser extension linked on the banner at the top of the extensions.gnome.org site.

It is probably worth mentioning that we are currently excluded from some distros official repos (at least Arch, anyway) due to not creating signed releases. So, that may be worth doing in the future to improve the number of repos the package is available in.

**Comment by damian101** [comment]
Thanks, that worked!
