### ISSUE TITLE
[Bug] The opacity settings only apply to panels not on the primary monitor

### ISSUE THREAD

**Issue by EnderShadow** [home-sweet-gnome/dash-to-panel#501]
The panel on my secondary monitor is translucent like it should be, but the main panel is the same color as the same color as the top bar.

**Comment by charlesg99** [comment]
Hello EnderShadow, thank you for the report! Could you please elaborate a bit? 

Could you provide a screenshot of your opacity settings and the panels?
What gnome-shell version are you on?
Are you using the latest dash to panel development version?
What theme are you using? 
Do you see errors in your log? 
Does it also happens if you disable every other extensions?

Thanks!

**Comment by EnderShadow** [comment]
Well this is odd. I've literally done nothing (not even rebooted the computer) and it appears to have fixed itself.
