### ISSUE TITLE
Setting the dash on primary screen only won't work

### ISSUE THREAD

**Issue by Spir** [home-sweet-gnome/dash-to-panel#551]
I have 3 monitors. My main monitor is tagged as number 3 on the system but is the one in the middle of my setup. When upgrading dash-to-panel to the latest version the dash moved to the monitor number 1. I tried everything on the setup of the extension the dash won't come to the primary. 
As a work around I changed the primary screen in gnome the the first monitor and was then able to set the dash to the monitor number 3 since he wasn't primary screen anymore.

Here is the config that won't work:

```
[/]
primary-monitor=1
shift-click-action='MINIMIZE'
shift-middle-click-action='LAUNCH'
panel-position='TOP'
dot-position='TOP'
intellihide=false
panel-size=32
multi-monitors=false
hotkeys-overlay-combo='TEMPORARILY'
show-activities-button=false
show-status-menu-all-monitors=true
isolate-monitors=false
appicon-margin=0
show-clock-all-monitors=true
show-favorites-all-monitors=true
middle-click-action='LAUNCH'
```

**Comment by jderose9** [comment]
I changed the behavior a little so that the drop-down has an option to basically keep the panel on gnome's primary monitor, whichever monitor that may be at the time, or to fix it to a specific monitor.

Unfortunately, using the same monitor label numbers from the Gnome display settings seems a bit difficult so I didn't tackle that.

Essentially, this was happening when the primary monitor index + the chosen monitor index was equal to the number of monitors. (ie. 2 monitors, gnome primary monitor was index 1 and panel monitor was set to 1, panel would go to monitor 0 due to [this line](https://github.com/home-sweet-gnome/dash-to-panel/blob/9676c01cdb4e7a5d36e994149e18f64a8433ba35/panelManager.js#L58)).

@Spir can you try the latest master and let me know if it is improved?

@charlesg99 Do you mind to review my commit and see if it makes sense and you agree with the change?

Thank you!

**Comment by charlesg99** [comment]
Makes sense to me! I tested this on wayland and xorg and it works as it should. Hopefully that fixes Spir's issue. Thanks!

**Comment by Spir** [comment]
@jderose9 using the "Default (Primary monitor)" and setting the primary monitor back to what I had is woking. 

But the other monitors settings are incorrect (the label monitors are different from the Gnome one's). For me:

- Monitor 1 is the primary but is actually number 3
- Monitor 2 is actually monitor 1
- Monitor 3 is monitor 2.

**Comment by jderose9** [comment]
It's not really a reasonable effort to get the monitor number to match Gnome's Control Center. Control Center fetches the displays from Mutter and sorts and labels the monitors on its own, and isn't necessarily running when the Dash-to-panel settings are open. The code isn't in the same language so it would have to be re-implemented to produce the same output. On top of that, the physical displays are labelled by control center, where gnome presents to us the logical monitors (for instance, mirrored displays appear as a single monitor).

We could probably display our own monitor labels, but I'm not sure when to trigger/hide them.

If you do cycle through the dropdown and find the particular monitor you need, it SHOULD stay on the monitor always (even through reboots, etc), though.
