### ISSUE TITLE
Wrong position for "Places status indicator"

### ISSUE THREAD

**Issue by aswild** [home-sweet-gnome/dash-to-panel#563]
When the built-in "Applications menu" and "Places status indicator" extensions are enabled, Dash to panel puts the Places menu to the right of the window list instead of to the left where it belongs (see screenshot 1 below).

I reproduced it in a clean Arch Linux VM:
* Install base system and create a user as usual
* Install gnome and gdm (gnome is at version 3.30 in the Arch repos)
* Start gdm, log in to a normal Gnome session (wayland or xorg doesn't matter)
* Install this extension (I used extensions.gnome.org with Firefox)
* With gnome-tweaks (or a browser), enable "Applications menu" and "Places status indicator"
* Enable dash to panel
* no other Gnome extensions enabled

If I reload (enable/disable) the "places status indicator" or "applications menu", the places menu jumps back to the correct location on the left. Unloading "applications menu" is actually enough to get the places menu back to the left side.

If I reload dash to panel with both other extensions disabled, it will go back to the broken layout.

Screenshot 1: broken layout
![image](https://user-images.githubusercontent.com/11742669/51066970-d65dbf80-15db-11e9-80f2-8e19da656b1f.png)

Screenshot 2: correct layout
![image](https://user-images.githubusercontent.com/11742669/51067154-66e8cf80-15dd-11e9-9cbb-fec76ab98943.png)

**Comment by charlesg99** [comment]
Hello aswild, thanks for bringing that up. All these extensions manipulate the top panel, so incompatibilities are bound to happen. To clarify, dash to panel doesn't move the other extension items, it does the same as the other extensions and inserts some elements in the top panel. In this case, dash to panel's taskbar (the icons) and the places menu button are both inserted at the second position of the left container of the top panel, so the extension enabled last will have its item correctly inserted at the second position while the other element gets scooched over to the third position.

I can reproduce the behavior you describe, but it only happens when forcibly enabling dash to panel after the places menu. If all extensions are enabled and gnome-shell is restarted, the layout ends up like your second screenshot, so this means that gnome-shell's extension system loads dash to panel first (on my system, but this is unreliable as the extension system uses GFileEnumerator, which orders the directories of the extensions to be loaded by their inode numbers, not alphabetically).

Just wanted to clarify what happens as this isn't really a bug in dash to panel, but rather a slight incompatibility between those 2 extensions :) 

Now as to how to fix this, I don't see a problem with just inserting dash to panel's taskbar after all elements present in the top panel's left container, instead of forcing the second position. From what I see, this should also work fine if the user has its taskbar positioned in the centerbox as well. @jderose9 do you see potential issues with this? 

Thanks!

**Comment by aswild** [comment]
Thanks  for the explanation!

On my desktop it does seem to layout right when I restart gnome-shell, but locking and unlocking the screen often messes it up. (current workaround is a script bound to a hotkey to reload the extension)

**Comment by jderose9** [comment]
@charlesg99 I think this makes sense for now. I recall seeing another extension that had capability of layout out the position of every panel element (I believe the "Taskbar" extension) and we may want to introduce that in the future.

We need to take the clock placement setting into account. We will also need to listen for additional actors to be added and re-position the taskbar (in case the places extension gets enabled later, for example). I'm a bit worried about other extensions competing with this one and trying to explicitly set their position (ie the actor-added getting infinitely fired because of the two extensions both listening and moving their panel elements). Although, I guess we haven't yet encountered this as a problem so far.

**Comment by charlesg99** [comment]
A fix was added to master, so the taskbar should always end up on the right. @aswild could you please confirm that it solves the issue?

@jderose9 Interesting idea to be able to just reposition everything... It should be fine for the clock placement as every position assigned is relative to another element, not a numeric index. The insertion of the taskbar was the only one using a fixed position index, but I'm pretty sure "2" was intended as the rightmost position (which was true most of the time).

Thanks!

**Comment by aswild** [comment]
@charlesg99 I just installed the latest master and it's working for me, everything looks to be in the right order. Thanks a bunch, this has been one of the best/fastest responses to an open-source project issue I've opened :+1:
