### ISSUE TITLE
Dash to Panel no longer works

### ISSUE THREAD

**Issue by ArsThaumaturgis** [home-sweet-gnome/dash-to-panel#567]
It seems that a recent update--whether to the OS, Gnome, or Dash to Panel itself I don't know, I'm afraid--resulted in Dash to Panel no longer working, where it had functioned well before.

Going to https://extensions.gnome.org/local/, I see an "error" marker beside Dash to Panel's entry (although to my frustration it doesn't indicate _what_ error that might be).

(I briefly tried disabling active extensions one-by-one via that page, but it didn't seem to affect the "error" marker beside Dash to Panel--but then, I don't know whether such an effect would be immediately visible, or would require a reloading of the page, or even a restart of the shell...)

I'm running Ubuntu 18.04.1 ("Bionic"), with the Gnome-version reported to be 3.28.2.

I'm not sure of what additional information might be of use in determining the source of the problem--please let me know so that I can (hopefully) retrieve it!

**Comment by charlesg99** [comment]
Hello ArsThaumaturgis, you can retrieve the error preventing the extension from loading by looking at your logs using `journalctl /usr/bin/gnome-shell`. The error should also be displayed in the looking glass. To check it out press `ALT-F2` then `lg`. In the looking glass window, on the top right you can select `Extensions`, then under dash to panel click on `show errors`.

We'll also need more info as I just tried v17, v18 and the latest master on an up to date ubuntu 18.04.1 (wayland and xorg) and couldn't reproduce the issue. Thanks!

**Comment by ArsThaumaturgis** [comment]
Ah, thank you for the response! I didn't know about the Looking Glass--thank you for mentioning it! ^_^

According to that, the error in question is this:
TypeError: Me is Null

The output from "journalctl" is... long. o_o Even reversing the output (thanks to the man-page) I'm seeing an awful lot of lines. Piping the output to "grep" turns up the same error given above.

Something did occur to me: I am using a custom theme, which may be somewhat half-baked: it's just one theme copied into a new folder, and various colour-values from another theme pasted as appropriate into its css files. (Gnome seems to make it quite a pain to customise the theming of one's system. >_<)

If there's a problem there--perhaps as a result of something being changed, and those changes being reflected in the standard themes but not the copy-pasted one--perhaps that's interfering with Dash to Panel? Perhaps there's some variable that was being used that no longer is, or something like that?

**Comment by ArsThaumaturgis** [comment]
Uninstalling and then re-installing didn't seem to solve the issue, I'm afraid. :/

It did appear to briefly do something, as the UI did change a little, with some of the dash (I think that it is) buttons disappearing, as I recall. However, restarting the shell and rebooting the computer both resulted in the UI resetting to its non-Dash-to-Panel form.

Switching the system's various theming-elements to their defaults didn't seem to have an effect, so at the least it seems unlikely that the issue lies with my dodgy theme!

Given the above, here is the output of the command that you indicated:
[journal_output.txt](https://github.com/home-sweet-gnome/dash-to-panel/files/2775085/journal_output.txt)

**Comment by charlesg99** [comment]
Does the issue persist if you disable the gnomenu extension? Does gnomenu works if dash to panel is disabled? Thanks!

**Comment by charlesg99** [comment]
Hey ArsThaumaturgis, thanks I could reproduce the issue.  After investigating, I can see that gno-menu is causing the extension loading process to stop, so whatever extension would be loaded after gno-menu isn't enabled at all. This can easily be reproduced by only enabling the "user-theme" extension and the gno-menu extension. We can then observe that the shell theme isn't loaded since user-theme can't be enabled. In that case, the same error occurs, but for user-theme:
`Extension "user-theme@gnome-shell-extensions.gcampax.github.com" had error: TypeError: Me is null`

The error from gno-menu is:
```
JS ERROR: Exception in callback for signal: hot-corners-changed: (null)
JS ERROR: InternalError: too much recursion
```

which is caused by an infinite loop started in gno-menu when it calls `Main.layoutManager._updateHotCorners();` from a handler that is triggered by the `hot-corners-changed` signal (this signal is emitted within the Main.layoutManager._updateHotCorners() function...).

This happens specifically on ubuntu because, by default it disables the top left hot corner (Tweak tool > Top Bar > Activities Overview Hot Corner), and the infinite loop only starts when there is no hot corner on the primary monitor. You can also verify this by enabling the hot corner via the tweak tool setting, then dash to panel and gno-menu are both loaded correctly.

I think the best thing to do would be to open an issue [over there](https://github.com/The-Panacea-Projects/Gnomenu).

Thanks!

**Comment by ArsThaumaturgis** [comment]
Ah, you're quite right! Activating the hot-corner seems to result in Dash to Panel working again! Thank you very much! ^_^

I may well take the hot-corner issue over to Gno-Menu's issue-tracker--thank you for the link!

I'll close this now, as it would indeed appear to be an issue with another extension entirely.

**Comment by charlesg99** [comment]
As a reference, it seems this issue was already fixed in Gnomenu repo: https://github.com/The-Panacea-Projects/Gnomenu/commit/a44d8a847f92a6348862acb5b83e4d7317658634

I guess it just isn't published yet on e.g.o.

**Comment by ArsThaumaturgis** [comment]
Ah, that's good to know--thank you! Hopefully it will come though on some future update. ^_^
