### ISSUE TITLE
SquishedTray Icons

### ISSUE THREAD

**Issue by AdmiralCode** [home-sweet-gnome/dash-to-panel#589]
Can a way be added to fix the height of tray icons?  On HiDPI displays, the icons end up getting squished.  See the pic.

![squished iconst](https://i.imgur.com/Yvfnt4Y.png "Tray Icons")

**Comment by charlesg99** [comment]
Hey AdmiralCode, which extension are you using to display the tray icons (Topicons plus, appIndicator)? Or are you on Ubuntu where it is enabled by default? Unfortunately, I think this will be another case where you will need to bring the issue to the other extension's people, since we aren't responsible for the placement/drawing of the tray icons. Thanks!
