### ISSUE TITLE
Has the Bottom Task bar / Panel changed with the latest update?

### ISSUE THREAD

**Issue by Lucapz** [home-sweet-gnome/dash-to-panel#606]
Ubuntu 18:10 with the latest extensions.gnome, Has something changed to the appearance of the latest release?

Are the icons on the bottom panel slightly bigger and is the panel colour a lighter grey?

Not that it bothers me if it has , i was just wondering if i was imagining things?

Thanks

**Comment by charlesg99** [comment]
Hello Lucapz, yes, because of an [issue on 3.32](https://github.com/home-sweet-gnome/dash-to-panel/issues/545#issuecomment-463201065), in the latest version the default panel opacity is handled a bit differently. That probably explains the slight color variation on Ubuntu that applies a default gradient on the panel. Same for the icons, they now scale independently of the running indicators height. Thanks!

**Comment by Lucapz** [comment]
Awesome , that would explain it , glad to know i wasn't imagining things as it's very subtle. :)

Thanks Charlesg99 , this can be closed.

**Comment by charlesg99** [comment]
Great!
