### ISSUE TITLE
Black border with transparency

### ISSUE THREAD

**Issue by cynecx** [home-sweet-gnome/dash-to-panel#612]
First of all, I am really sorry if this isn't the right place but I am not exactly sure what the exact origin of this issue is.

![black corner](https://user-images.githubusercontent.com/5961244/55094479-c3c13580-50b6-11e9-813a-710384221d23.png)

Just below the application button, you can see a black area which didn't exist before my upgrade to gnome 3.32 / DTP v19.

Distro: Arch
GNOME: 3.32
DTP: v19
Theme: Arc-Dark (App) / Default(Shell)

**Comment by charlesg99** [comment]
Hello cynecx, thank you for the report! Yes indeed those are the panel corners which have been [reverted to fully black/opaque in 3.32](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/376) (that is why they "pop" so much). Never noticed them since they're under the panel and I set mine at the bottom of the screen :smile:. I also think that arc-dark, when applied to the shell, removes those corners.

Looking at the issue, I noticed that those corners weren't affected by the value set by the explicit panel opacity found in dtp settings. I added a fix to master that should bind the corners opacity to the panel one, could you let us know if that fixes the issue on your end? Thanks!

**Comment by cynecx** [comment]
@charlesg99 I've just tested out the master branch and it seems to work just fine! Thank You for the quick fix!
