### ISSUE TITLE
The Button "Show appliactions" is a little blurred

### ISSUE THREAD

**Issue by Alexander88207** [home-sweet-gnome/dash-to-panel#627]
![Bildschirmfoto von 2019-04-22 13-26-50](https://user-images.githubusercontent.com/37543796/56498519-4e545380-6502-11e9-807e-aa537babbcee.png)

gnome-shell: 3.30.2-r1
panel size: 32

**Comment by charlesg99** [comment]
Hello Alexander88207, I had a look and I don't think we can do much about it (on the dash to panel side), unfortunately. This is an svg scaling issue with the show application icon `view-app-grid-symbolic` that uses Cubic Bézier Curves.

What you can do to make it crisp is to ensure that `panel size - icon padding * 2 = factor of 16` (since the icon is defined as 16x16). This way the show application icon should be rendered without any blur. For example, if you set your panel size to 32, you would need to set your icon padding to 0 to get the crisp icon. If you want some icon padding, let's say 2, you would need to set the panel size to 36 (`36 - 2 * 2 = 32` and `16|32`). Hope that makes sense! 

Thanks!

**Comment by Alexander88207** [comment]
Alright, thanks for the clarification.
