### ISSUE TITLE
Some applications are not grouping

### ISSUE THREAD

**Issue by eyun89** [home-sweet-gnome/dash-to-panel#643]
Gnome Version: 3.32.1
Dash-to-Panel Version: 19
___
I have Dash-to-Panel configured to group applications. All applications I normally use seems to be grouped correctly (i.e Firefox, Gnome Terminal, VSCode). 

I've just install [KDE Dolphin](https://kde.org/applications/system/dolphin/) but the instances are not grouping.

What am I doing wrong?

Thanks so much for all your efforts working on this extension!

**Comment by jderose9** [comment]
Hi @eyun89 ! This is due to a mising StartupWMClass property in the .desktop file for Dolphin. This would happen in the GNOME dash even without dash-to-panel.

You can either fix it manually or use @bilelmoussaoui 's script to fix it, found here:
https://github.com/bilelmoussaoui/StartupWMClassFixer

**Comment by qoheniac** [comment]
And maybe consider [filing a bug report](https://bugs.kde.org/enter_bug.cgi?product=dolphin). I did that for Okular [here](https://bugs.kde.org/show_bug.cgi?id=439552) and they added StartupWMClass to their .desktop file.
