### ISSUE TITLE
[Feature request?] Options to configure the clock/date

### ISSUE THREAD

**Issue by youngbasta** [home-sweet-gnome/dash-to-panel#645]
The clock/date isn't the best in the world. Do you think you could add more options to configure it? Change the date display type and on what side to put the date and time. I was thinking a little like the Budgie desktop. But you can customize it more.

I am using version 19, 3.30.2

**Comment by charlesg99** [comment]
Hello youngbasta, there already are some extensions allowing you to customize the clock format and they work just fine alongside dash to panel, so I don't think this needs to be duplicated. Here is a good one to try: https://extensions.gnome.org/extension/1206/clock-override/

As for the clock placement, I think the current offered options should cover most use cases:

![image](https://user-images.githubusercontent.com/33044886/57557458-39702080-7348-11e9-9f5b-2f96008933a0.png)

Thanks!

**Comment by youngbasta** [comment]
Thanks, that worked well. But doesn't adding too many extensions add a higher risk of crashing or adding malicious code to it all. I was more thinking you could add more customization to it, so less extensions can be used :P Just a thought?

**Comment by charlesg99** [comment]
Having many extensions doesn't really add risks of crashing, but makes it more likely to encounter incompatibilities. In our present case, since we know both extensions can happily coexist, I don't see a benefit in duplicating development/maintenance efforts. 

Also, if you get your extensions from [e.g.o.](https://extensions.gnome.org), this site does review extensions for potential malicious code before publishing them. Unless you're personally screening all of your extensions code before installing them (I know I don't) it is the next best thing. 

Thanks!
