### ISSUE TITLE
Feature request: taskbar position left or right margin advanced setting

### ISSUE THREAD

**Issue by luispabon** [home-sweet-gnome/dash-to-panel#651]
I'm using d2p with unite, and so far so good, everything seems to work together amazingly well.

There's one thing though that's a little jarring and is elements on the panel moving as the window controls are inserted:

![image](https://user-images.githubusercontent.com/6388823/57969928-b3b92a00-7972-11e9-8be2-8369f94206ba.png)
![image](https://user-images.githubusercontent.com/6388823/57969937-c469a000-7972-11e9-99bf-5ed32bb77c40.png)
 
This is not an issue when setting the taskbar at "center, fixed position", but then the taskbar is somewhere I don't want it to be.

I was wondering if it would be possible to add a setting to have it "left, fixed position" with an additional configurable x coordinate. That way I can have the window controls popping in and out without moving the taskbar, while still looking like the first screenshot.

**Comment by charlesg99** [comment]
Hello luispabon, sorry but the issue clearly stems from an incompatibility with the Unite extension. Adding a setting/code solely to mitigate the incompatibility isn't a good idea to me. Maybe the [Unite folks](https://github.com/hardpixel/unite-shell/issues) could keep the window controls in the panel, but have them invisible while unneeded instead of removing them (so the space would still be occupied? Anyway closing for now as this is too specific. Thanks!
