### ISSUE TITLE
Right click on a thumbnail will open the WM menu

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#665]
**Reproduce**
1. Hover over an open app to trigger the preview
2. Right click over the preview

**Result:** The WM menu opens, and additionally it does not work

**Expected:** no idea :)

![Screenshot from 2019-06-20 12-20-49](https://user-images.githubusercontent.com/11244308/59837710-5be95680-9356-11e9-9df0-a052d0ef7107.png)

**Comment by charlesg99** [comment]
Hello alex285! Yes the context menu is intentional (it is also present in the previews on master), we even added the item "move to current workspace" following #654. 

The context menu works fine on 3.32, but is indeed broken on 3.34. I don't think it's dash to panel related though. You can try right clicking on a window title bar to get the same menu and you'll see that the menu isn't working there as well. Not sure why, but my guess would be the ".actor" purge that is going on in gnome-shell at the moment. Thanks!

**Comment by alex285** [comment]
>  You can try right clicking on a window title bar to get the same menu and you'll see that the menu isn't working there as well.

oh, right! i should have thought of that before open it, because i knew that bug already! sorry! closing it!!
