### ISSUE TITLE
[Feature Request]option to have different background colour for apps(task bar) section and icons(of system&plugins) section.

### ISSUE THREAD

**Issue by narasimhajupally** [home-sweet-gnome/dash-to-panel#693]
we know that the system tray icons colour fixed most of the time whereas the apps have themes.
(eg. if we set the panel to be transparent then there will be difficulty for viewing the system tray icons )
so having separate backgrounds (overlapping the common background) for the two sections we have in the panel can open different ways of customizing the look of the panel.
if we have different background colour to taskbar then a option to set border-radius to it will be so cool.

More power to the king!!!, thank you.

**Comment by charlesg99** [comment]
Hello narasimhajupally, I think this is the same feature request as #604. I would close this if this is the case. Thanks!

**Comment by narasimhajupally** [comment]
yea it is similar. i just described in detail how to attain notch.Ability to set different heights and different background colors for different sections of the panel.

**Comment by PranavBhattarai** [comment]
yes, making time & data area permanent dark (because it makes them invisible if when we try to view it on the transparent background where the background is white.) and making the rest of the panel clickable would have been awesome.

//when I mean "clickable", I meant like as a free space where we can touch terminal, windows, scroll things, etc. Instead of dedicating that area as for panel. An option like this would be very cool.

**Comment by jderose9** [comment]
I don't think we will be able to implement this. We don't have a "time & data area", but instead widgets that an be added to the panel in any order or location. To have clickable content in the background, we would have to break the panel into multiple separate panels and I just don't see much use case given the high amount of effort for that. There is an outstanding issue to set a non-100% width to the panel which we do plan to implement some time, but not to separate into multiple distinct regions/panels. Thanks for understanding!

**Comment by PranavBhattarai** [comment]
I know for now, "Plano theme" can be use where "time & data" section can remain always "black on white" format which makes time and date visible if u use white background or a blackground making rest of the area completely transparent. 

But I don't like this dependency on "Plano theme". Can't we provide this feature on Dash to Panel under settings of "in what way u want make panel to look transparent" section. (Idk where transparent option reside since right since I am using mobile right now).

Because currently making panel transparent makes everything worse. You need to use black wallpaper if which be considered. But you browser website with black ground. Every linux with black browser. Precisely. Which is nuts to maintain. 

(Plano is not actively maintained. Its barely maintained. And it change a lot of options things in shell which I don't need when it's buggy.)

@jderose9 what do you think about this?!
