### ISSUE TITLE
Preview on click only

### ISSUE THREAD

**Issue by bitstrings** [home-sweet-gnome/dash-to-panel#696]
I can't seem to simply have preview on click only.

The click action is set to toggle single / preview but that does nothing.

It would be cool to have preview on hover disabled and click for preview.

**Comment by ToxicDragon** [comment]
+1 for this! When coming from Windows, this is exactly the behaviour someone might expect. Additionally, when accidentally hovering the task icon with the mouse when actually wanting to e.g. only switch browser tabs on a maximized browser, it is quite annoying that the window previews appear.

Actually, this proposed behaviour could easily be implemented as follows:
1. Deactivation of window previews on hover (already implemented)
2. Add preview of windows as "onClick" action in the corresponding dropdown setting

IMO this would also satisfy the usability of the settings page and probably be easily implementable?

Thank you in advance and keep up the really great work in making usability of the whole Gnome shell great again ;-)

**Comment by jderose9** [comment]
`Toggle Single / Preview Multiple` when assigned to the left mouse button is designed to replicate the Windows behavior. In windows, if you only have a single window for an application, it will toggle between restore/minimize when you left click. When you have multiple windows, it will open the preview thumbnails instead. Does this cover what you are looking for?

**Comment by bitstrings** [comment]
Mmm... That's the thing. It doesn't work here. Actually, it never worked. Lets say I disable preview on hover and activate `Toggle Single / Preview Multiple`, the previews will never appear and toggle doesn't work either.

**Comment by jderose9** [comment]
@bitstrings I think this is just poor wording in the configuration. Try to leave the preview on hover ON instead of off, with Toggle Single/Preview Multiple selected as the left click action.

**Comment by bitstrings** [comment]
I tried that, but it doesn't work. To test this, use 2000 as the time before showing and even if I click on the icon it doesn't show the preview.

**Comment by jderose9** [comment]
@bitstrings does it show it if you have multiple instances of the application running? (Multiple windows)

**Comment by bitstrings** [comment]
Here is the behavior I get, if I use `Toggle Single/Preview` and 2000 as the time before showing:

Let's say I use Firefox:

- Only 1 firefox open, then if I click icon I get the normal behavior of minimize/maximize and if I leave the cursor on the icon for 2000ms then I get the preview.
- 3 firefox open, then if I click icon and nothing happens and if I leave the cursor on the icon for 2000ms then I get the preview.

**Comment by ToxicDragon** [comment]
@jderose9 @bitstrings I had a look in the code and the TOGGLE-SHOWPREVIEW buttonAction acutally does not toggle the preview windows at all. And it is not the desired behaviour to have the "Hover preview windows" global option checked.

Therefore, I just coded the necessary logic and made a pull request #699  :) You can check out my pull request or clone my forked repository if you need the behaviour in the meantime. Hope this gets merged (soon or at all ;) ).

@jderose9 @charlesg99 Could you give me the right to add branches to the repo? Therefore, I would not need to fork your repo and add pull requests from my fork... thx!

**Comment by jderose9** [comment]
This was behavior added in #553. The spirit of that addition was to replicate windows. Generally speaking, I think that's a good goal as many users are coming here from Windows.

@ToxicDragon  Regarding the pull request - first, thank you for taking the time.

My main concern is that I think by toggling the preview, we may cause some grief for existing users. The previous behavior I think was geared toward a user that just wanted to click the button without being conscious of how many windows were open or what the state of the previews was already - it would open a single window if it could, or otherwise force them to make a decision. This is sort of what I think Windows is after, and definitely follows the KDE icon taskbar behavior. Maybe @ihsankavalci wants to chime in on that?

In the toggling scenario, it seems a little odd that the previews only get toggled by clicking an icon with multiple windows open, so I can only see the preview of a single-window app by first clicking on a multi-window app and then sliding over. And I'm thinking that @bitstrings was suggesting we toggle on click regardless of how many windows were available. I'm wondering if the best option is to treat your behavior as a new "Toggle Previews" option, and toggle the previews regardless of how many windows are available. What do you think?

There's one other issue I see which is that there is no way to customize the window previews if you have the hover turned off. This isn't really a new issue, but previously the clickable previews were essentially off when the hover was off (which I think was wrong), but now this is no longer true. We could stop disabling the settings button when the hover is off I guess - I can't think of another quick fix without reworking the settings UI?

Lastly, a fork with a pull-request is the preferred workflow for this. Thank you!

**Comment by charlesg99** [comment]
I agree with Jason here, disabling the previews on hover when that option is enabled in the settings is quite confusing. I think the main issue was to be able to show the previews on click only, so a fix for this was added to master. 

This small and localized change makes it that when the "show window previews on hover" is enabled, the hover behavior stays the same, except that the previews can be toggled on/off with a click on an appicon having more than one window associated to it. Also, when the "show window previews on hover" is disabled, it is now possible to show the previews on click only, which is, I believe, the behavior that bitstrings was originally seeking.

Thanks!

**Comment by ToxicDragon** [comment]
Hi there,
@charlesg99 Just checked out your work; from a usability perspective (not code perspective ;) ) this is actually quite identical to my solution (have you tried it?). The only thing different is that when TOGGLE-SHOWPREVIEW is activated and the hover option is not activated, and the window preview is already open for application A and you then put the cursor on the open application B -> The window preview for application B is not shown, but rather the one from application A stays activated.

Actually I don't know which version would be better from a usability perspective, because I see reasons for both of them. However, it is not my project and therefore, this of course is up to you guys :) What I really appreciate is your responsiveness and taking action; really nice, thx!

Additionally, I just checked my old Windows 10 notebook for how the windows preview work there; I have to admit that I remembered incorrectly; Windows 10 shows the previews on hover, not on click. However, the preview windows themselves are smaller; I guess the bigger default sizes are the reason I had problems with them.

So @charlesg99 @jderose9, now that I have read through quite some bits of your code: If there is something else to tackle, just tell me :) I am currently on vacation and maybe have some free time left to tackle things :)

**Comment by jderose9** [comment]
I tend towards the @charlesg99 implementation because it is less of a departure from the existing behavior for that option, though I think ultimately it just comes down to personal preference.

I do have a couple of questions:

1) Is keeping the the gear icon next to the hover preview setting enabled a satisfactory solution to allow someone that might have hover disabled but previews setup as a click action still customize the previews?

2) @bitstrings Are you looking for another setting to toggle previews on click action regardless of how many windows there are?

@ToxicDragon You are welcome to take a stab at any of the open work items. There should be at least a couple tagged "Good first issue".

**Comment by charlesg99** [comment]
Hey guys, I also checked Windows 10 and it is indeed the same behavior as before the modification! 

To me this doesn't feel like an issue though since, when the "previews on hover" is enabled, the only difference from Windows is that the previews can be toggled with a click on the appIcon. Then again, I'm not using this option so I'm probably not a good reference on its usability.

@jderose9 I personally don't think the disabled gear icon is a big issue in this case as it should make sense to the majority of users. I also don't mind leaving it enabled when the previews on hover are disabled, so it's your call :)

@ToxicDragon Yes I did try your fork before doing the modification and I also forgot to thank you for submitting it, so Thank you! I encountered some funkiness with the previews/tooltips and since it wasn't a long fix, I just did it instead of trying to have you fix yours. Sorry, I hope I didn't overstep, it's just we're a bit short on time with the e.g.o. review process being crazy long again and 3.34 around the corner. Please be sure to check the opened issues if you want to contribute further. FYI so you don't accuse me of speaking nonsense, here is the fumiest I saw when trying your fork :) 

![Peek 2019-08-13 12-47](https://user-images.githubusercontent.com/33044886/62960377-842a8a00-bdc8-11e9-968e-8ec8a18e3082.gif)

**Comment by ToxicDragon** [comment]
@charlesg99 Everything's fine :) It is superb that this feature is already in master. This matters most for me (and I guess other users). Thx!
