### ISSUE TITLE
Menus shifting when expanding submenus

### ISSUE THREAD

**Issue by viggy96** [home-sweet-gnome/dash-to-panel#698]
I screen recorded the issue here: https://streamable.com/3uopi

Hopefully the issue is clear in that recording.

Manjaro stable, GNOME 3.32.2, kernel 5.2.4-1
AMD graphics, Mesa 19.1.3

**Comment by charlesg99** [comment]
Hello, this does look like a theming issue to me... Do you see the same shift when Dash to Panel is disabled? With the default Adwaita theme? Thanks!

**Comment by viggy96** [comment]
Yes, this issue occurs even with the default theme.

**Comment by charlesg99** [comment]
How about when Dash to Panel is disabled? Should be the same as we aren't creating/touching those menus... Thanks!

**Comment by charlesg99** [comment]
Well I just tested this and the same can be observed on vanilla gnome-shell. Maybe you could open an issue over [there](https://gitlab.gnome.org/GNOME/gnome-shell/issues)? Thanks!

**Comment by viggy96** [comment]
I don't see this behavior when Dash to Panel is disabled, which is why I posted the issue here. For example, I'm using Dash to Dock right now, with a stock top bar, and the menus do not shift, even with a custom theme.

**Comment by charlesg99** [comment]
Sorry, I should have explained better. You are right, it does appear to shift a little bit when the panel is at the bottom, but not when the panel is at the top like the gnome-shell's top bar. 

This happens because opening a submenu changes the height of the boxpointer by expanding and changing font's weight. When the boxpointer is at the top, its top position is fixed, so animating only its height is enough, which makes the shift a lot less noticeable. When the boxpointer is at the bottom, both its top position and its height are animated at the same time. Since the positions, being dependent on the heights of the boxpointer's elements, are [being rounded](https://gitlab.gnome.org/GNOME/gnome-shell/blob/master/js/ui/boxpointer.js#L575), the shift you reported can be observed.

As an example, notice the jumpy bottom edge of the boxpointer here while its top position is being rounded:

![Peek 2019-08-16 18-14](https://user-images.githubusercontent.com/33044886/63201089-d205f300-c051-11e9-8023-c5b573552b7d.gif)


In the next example, the rounding of the boxpointer's top position has been removed (from g-s code) and you can see that the bottom edge no longer jumps around. The same principle applies to every height/positioning combo that you see in the boxpointer.

![Peek 2019-08-16 18-16](https://user-images.githubusercontent.com/33044886/63201182-1a251580-c052-11e9-8bdb-92e4fcc89442.gif)


Conclusion, this comes from the gnome-shell code, but isn't an issue it their case since the panel is always at the top. Hope this makes sense, thanks!
