### ISSUE TITLE
Delay for when scrolling over the panel

### ISSUE THREAD

**Issue by sojusnik** [home-sweet-gnome/dash-to-panel#705]
A configurable delay when scrolling over the panel to change workspaces, like [this](https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/) extension has, would be very helpful for those with a sensitive mouse wheel.

**Comment by charlesg99** [comment]
Hello, thank you for the suggestion. I really wish we could have gotten away with it without having to add yet more settings :) I do understand that, since it replaces the extension you mentioned, it would be appropriate to include similar settings or at least allow the user to disable our implementation so "Top panel workspace scroll" would still work.

@jderose9 I think another settings split is in order? I would create another settings tab called "Action" in which we could move the "click action" and the hotkey settings, as well as include the new panel and appicon mouse scroll actions (enabled or not as well as the delay mentioned in this issue). What do you think?

**Comment by jderose9** [comment]
@charlesg99 I think that makes sense. It does seem like we will need to allow the user to disable the window and workspace switching via scroll, at minimum.

**Comment by charlesg99** [comment]
Hello, as discussed, options to disable the scrolling actions, as well as to limit the number of captured events were added to master. Thanks!
