### ISSUE TITLE
Mouse scroll wheel adjust volume

### ISSUE THREAD

**Issue by llcool** [home-sweet-gnome/dash-to-panel#707]
When using the mouse scroll wheel to adjust volume, scrolling also changes the workspace. Related to #486

**Comment by charlesg99** [comment]
Yes, thank you for bringing this up, this issue was already reported/fixed yesterday, see #702. If this is a real grief to you, for now please install the master branch. I think we should wait a few days to see if other issues related to v21 are reported, then release a maintenance version on e.g.o. Thanks!
