### ISSUE TITLE
Crash on Isolated workspace switch (g-s 3.28)

### ISSUE THREAD

**Issue by mikula-espirit** [home-sweet-gnome/dash-to-panel#721]
Hey there,
I'm on:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
I've upgraded to version 22 today (I'm sorry but i don't know what version i was on before). 

The isolate workspaces feature worked fine until the upgrade. If I try to switch the workspaces now using: ctrl + alt + (up/down). I do get a black screen or my gnome desktop crashes and I have to login again.

Is there any more information you need? I really need that workspace feature back ;)

**Comment by mikula-espirit** [comment]
I've switched to version 20. It works fine there.

**Comment by charlesg99** [comment]
Hello mikula-espirit, yes sorry about that and thank you for the report! This issue is already fixed on the master branch and should be released very soon with v23. Feel free to [install master](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github) until v23 is available on e.g.o. Thanks!
