### ISSUE TITLE
[Feature Request] Ability to disable numpad for Super+1, Super+2, etc. keyboard shortcuts

### ISSUE THREAD

**Issue by akoyich** [home-sweet-gnome/dash-to-panel#724]
I love the dash-to-panel extension. Because I use so many custom keyboard shortcuts that use the numpad (keypad, whatever you want to call it), I would like to be able to keep the hotkeys to launch/switch to apps (e.g., Super+1), but have it so it only uses the number row, and not the numbers on the numpad. Is this easily doable?

**Comment by charlesg99** [comment]
Hello akoyich! Good idea, thank you for the suggestion! Some changes are currently making it more convenient to add this on an unrelated feature branch... 

The ability to select which number keys activate the hotkeys was just added to the `vertical-panel` branch. Could you please install it ([see here](https://github.com/home-sweet-gnome/dash-to-panel/issues/3#issuecomment-529162697)) and tell us if this is what you had in mind? This way you also help us with the testing :smile: 

Thanks!

**Comment by akoyich** [comment]
Awesome! Thanks so much. This is exactly what I was looking for.

**Comment by akoyich** [comment]
One question: I can use Super+Ctrl+[number] to open a new instance of an application. This works for all my apps except for Nemo. Do you know why? (I know this isn't related to the Gnome extension, but thought I'd ask anyway.)

**Comment by charlesg99** [comment]
Hey akoyich! Thanks for the feedback! 

As to your question regarding applications startup, it really depends on the application itself. We have some logic to check the "preferred" behavior (if the application declares it), but otherwise we just try to start a new instance. In the Nemo case, it _looks like_ (I didn't dig deep enough to confirm that) it always runs as a single instance, as you can see in its [initialization](https://github.com/linuxmint/nemo/blob/0371d6e875512573b730653214078b784b5a8383/src/nemo-main.c#L97).
