### ISSUE TITLE
System tray icons only showing on the first monitor

### ISSUE THREAD

**Issue by corrilan** [home-sweet-gnome/dash-to-panel#735]
Hello

I have found that when using applications that place icons in the system tray (such as KeePassXC), the system tray icon for the application only appears on the first monitor of a multi monitor system.

As can be seen from the screenshot below, the green KeePassXC icon just to the left of the date/time is showing as this screenshot is from my primary monitor.  My other 2 monitors do not show this icon.

<img src="https://www.corrilan.com/system-tray-icon-issue.png"/>

Regards

Jason

**Comment by charlesg99** [comment]
Hello Jason, the tray icons are brought to the panel by another of your extensions (Topicons plus, appindicator, etc.). Since this responsibility doesn't belong to dash to panel, it would be better to submit the issue to the extension you're using for this purpose. We are currently providing an easy way to other extensions who want to access our panels, so it should be fairly easy to implement (i.e. this is how Arc-Menu displays its menu on all panels). Thanks!
