### ISSUE TITLE
a horrible bug when teamviewer is open

### ISSUE THREAD

**Issue by loaderini** [home-sweet-gnome/dash-to-panel#750]
This has happened every time I opened teamviewer (installed from the [official .deb](https://download.teamviewer.com/download/linux/teamviewer_amd64.deb)) while having dash-to-panel activated (no other extensions activated) in Ubuntu 19.04 x64. The dash-panel starts behaving strangely, minimize-maximize does not work on every click and, worst of all, if a 'white' menu appears, that's it, I'm screwd. I cannot go back and I have to press reset on the computer tower :/ When I say 'white' menu I mean the menus for entering user password and wifi selection. Those menus are always white, even when I have the _Yaru-dark_ theme activated.

The system doesn't even freeze when the 'white' menus appear. Today I had a video on VLC playing, and then I opened the wifi selection list. The video was playing normally while I could do nothing to get out of that menu: escape, alt-tab, alt-f2 (actually I tried every _alt-f_ combination), alt-ctrl-del, alt-ctrl-T, nothing worked.

Does this happen to anybody else? I use teamviewer a lot, so today after I had to reset my computer again and again, I decided to format and install Mint Cinnamon. I tried to reproduce the problem in Cinnamon, but it did not happen. Is it possible for someone to find out if this can be fixed? I really liked Ubuntu with Gnome and I'd love to go back to it, but I also need to be able to use teamviewer!

**Comment by charlesg99** [comment]
Hello loaderini, I'm using Teamviewer regularly and never encountered such issues. Not saying there is no problem on your system, but I'm fairly sure this isn't dash to panel related. To make sure, I also installed on Ubuntu 19.04 the .deb you used and everything works properly for me. 

Sorry, but unless you can provide a clear way of reproducing the issue that demonstrates that it is caused by dash to panel, there isn't much we can do. We'll reopen then, thanks!
