### ISSUE TITLE
Time position

### ISSUE THREAD

**Issue by ktamp** [home-sweet-gnome/dash-to-panel#773]
Could there be an option to have the clock displayed at the far left of the panel independent of the taskbar position? This would allow for a scenario where the following conditions coexist:
* The complete date/time is displayed by the clock.
* The taskbar is centered.
* The taskbar utilizes the maximum possible space for displaying icons.

**Comment by Shini31** [comment]
An option for time centered will be awesome

**Comment by cyan-lime** [comment]
Came here looking for this as it's something I was disappointed to find I couldn't do today. +1

**Comment by smichel17** [comment]
It took me a while to figure out how to get the clock to appear in gnome 3's default center position. Turns out it is possible with the following two settings:

- Taskbar position: `Left, with fixed center plugin icons`
- Clock location: `Left of plugin icons`

This causes the clock to appear 1-2 pixels different from where it does with the extension disabled. Perhaps I could fix this by tweaking padding values, but I'm not going to bother; I can't tell the difference unless I do a side-by-side comparison by toggling this extension on and off.

**Comment by jhpratt** [comment]
I'd like to be able to do this as well. What @smichel17 recommends works if you want the clock in the center, but I'd prefer to have clock/apps/everything else as left/center/right. Though I'd also prefer to have the window title in the bar (a la [GTK Title Bar](https://extensions.gnome.org/extension/1732/gtk-title-bar/)).

**Comment by charlesg99** [comment]
Hello the new positioning options allow these configurations. Please install the latest master to use it. Thanks!
