### ISSUE TITLE
Inconsistent behaviour with "Show window previews on hover"

### ISSUE THREAD

**Issue by EMH-Mark-I** [home-sweet-gnome/dash-to-panel#782]
With DTP on the newer Ubuntu 19.10 release, I've noticed some inconsistent behaviour with the window preview feature. I suspect that this might be a bug.

Occasionally the task preview feature stops functioning until I click an active task, then it will work.

The task preview thumbnail will appear as an unaligned empty box; as seen in the following gif:
![Peek 2019-10-24 11-55](https://user-images.githubusercontent.com/28378002/67507841-647bd180-f655-11e9-9529-c632d3c9c46e.gif)

I've disabled all of the shell extensions except for DTP and this will still occur. This makes it difficult to select grouped tasks. I believe this has something to do with minimizing applications.

Thank-you

----

GNOME Shell version: 3.34.1
Dash to Panel version: 23
OS: Pop!_OS 19.10

Installed extensions:

Alt Tab: Raise First Window 
Always Show Workspaces 
Do Not Disturb 
Pop Battery Icon Fix 
Pop Shop Details 
Suspend Button 
User Themes 
Workspace Indicator

**Comment by charlesg99** [comment]
Hello EMH-Mark-I, thank you for the detailed report! This issue, introduced by gnome-shell 3.34, was already reported about a month ago (see #743) and the fix for it should soon be available on e.g.o. as a part of the pending [v24 release](https://extensions.gnome.org/review/12682). If you can't wait, please install from the GitHub repository following [these instructions](https://github.com/home-sweet-gnome/dash-to-panel/wiki/Installation#installation-from-github). Thanks!

**Comment by EMH-Mark-I** [comment]
@charlesg99 

That's great, thanks! You can close this issue if necessary then since it's a duplicate.
