### ISSUE TITLE
Stopped working with "Remove Dropdown Arrow" Extension

### ISSUE THREAD

**Issue by sojusnik** [home-sweet-gnome/dash-to-panel#790]
After installing v25 of Dash to Panel, the dropdown arrows appeared again although the "[Remove Dropdown Arrow](https://extensions.gnome.org/extension/800/remove-dropdown-arrows/)" Extension is enabled. When Dash to Panel is deactivated, then the arrows are gone too. Happens on Ubuntu 19.04.

**Comment by evgenyz** [comment]
Drop Down Terminal and Straight Top Bar are also broken with this update.

**Comment by charlesg99** [comment]
Hi guys, yes you're right, the reason is that we had to stop using the default gnome-shell panel on the primary monitor as it was interfering with the new vertical layout (a lot of stuff in gnome-shell is calculated based on the height of the default top panel... imagine what it does when its height equals your monitor's). Instead we are now "stealing" its content (leftBox, centerBox, and rightBox) and creating our own boxes for the additional monitors (this part hasn't changed).

We also created a simple way for other extensions to use our panels, like [Arc-Menu does](https://gitlab.com/LinxGem33/Arc-Menu/blob/master/extension.js#L68) to support multi-monitors. Of course this isn't ideal as other extensions would need to adjust to our panels, but at least this gives you the rationale behind this change. 

I'll try to see if it would be possible to "proxy" the default gnome-shell panel to our panel on the primary monitor.

Thanks!

**Comment by digiberk** [comment]
Would it be possible to implement a setting where we can remove dropdown arrows directly form Dash to Panel extension instead of relying on another extension? Then we can have a super-flush taskbar! :)

**Comment by charlesg99** [comment]
Hello, this should now be back to "normal" on the master branch as we are once again using the main panel on the primary screen. Could you confirm that it works on your end? Thanks!

**Comment by charlesg99** [comment]
This should be fixed (see #811). Closing for now, we can reopen if need be. Thanks!
