### ISSUE TITLE
Clone extensions to all monitors

### ISSUE THREAD

**Issue by saintusmarcus** [home-sweet-gnome/dash-to-panel#794]
Currently, any installed extension that adds funcionality to the panel such as the [AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) or [Sound Input & Output Device Chooser](https://extensions.gnome.org/extension/906/sound-output-device-chooser/) only works on the primary monitor instead of all monitors. This creates a discrepancy between monitors, meaning that, for example, playing a game in fullscreen on the main monitor makes it impossible to use these extensions. I'd appreciate it if there was an option to clone extensions to other monitors, if possible.

**Comment by charlesg99** [comment]
Hello saintusmarcus, unfortunately I don't think this is something that we can reasonably do. Extensions can change pretty much everything in the gnome-shell interface and there isn't a reliable way to detect all of those changes. We could try to detect the most common ones, but I fear it would be lackluster at best.

IMHO, the other way around is how it should be done. We're already providing other extensions with a way to utilize all our panels instead of the default gnome-shell top panel (i.e. see Arc-Menu's [multi-monitor support](https://gitlab.com/LinxGem33/Arc-Menu/-/wiki_pages/General-Tab#3-display-on-all-monitors-when-using-dash-to-panel)). I would suggest that you submit issues to the extension repos that you'd like to see on all monitors.

Thanks!

**Comment by jderose9** [comment]
I agree with @charlesg99 but wanted to add that you can change the primary monitor for the extension, which is different than the primary monitor set in gnome (which your game will appear on).
