### ISSUE TITLE
'Show desktop' not working anymore 

### ISSUE THREAD

**Issue by Hotteterre** [home-sweet-gnome/dash-to-panel#798]
Hello,
thank you for the great work! Since I updated to Gnome 3.34.1, hoovering on 'Show desktop' button doesn't work anymore with some apps - I noticed it with Firefox, Thunderbird, LibreOffice and Frescobaldi. If other windows are opened, it reveals them in transparency, but not the desktop.
Thank you!!!

**Comment by charlesg99** [comment]
Hi Hotteterre! Yes unfortunately we can't do much about it from Dash to Panel as it's a mutter bug that was introduced with 3.34. Please see https://gitlab.gnome.org/GNOME/mutter/issues/836 to contribute further or follow its development. Thanks!

**Comment by Hotteterre** [comment]
Thank you! :-)

**Comment by charlesg99** [comment]
Well, since we can't know for sure how long it's going to take for the mutter bug to get fixed, I added a workaround to immediately hide the windows instead of fading them... This is a bit more abrupt, but it's the best we can do for now. If this mutter bug ever get fixed, I'll restore the fade effect. Thanks!

**Comment by Hotteterre** [comment]
Wow, thank you!
