### ISSUE TITLE
(Intellihide) Panel hides when entering menu

### ISSUE THREAD

**Issue by 16NoCo** [home-sweet-gnome/dash-to-panel#813]
With Intellihide enabled, and when the panel is by default hidden because of a window obstructing it:
when I reveal the panel and click to open a menu, the panel hides back when the mouse leaves the panel area (after specified delay).

This cause the menu to "jump" up (because panel is on top), but only when the mouse clicks or moves again.
The main issue being that the click often triggers the wrong element (example in the gif below: trying to select belgian keyboard, but clicks on japanese).

This only happens with the 'system indicators' and system tray menus: right-click menu on taskbar and 'show apps' does not let the panel disappear.

I'm using version 26 on Ubuntu 18.04, Gnome 3.28, Xorg

![Peek 2019-11-16 22-01](https://user-images.githubusercontent.com/26925557/68999153-bf9f8d80-08bc-11ea-8bdc-541588497c01.gif)

**Comment by charlesg99** [comment]
Hello, this issue was reported in #795 and the fix was released with v26. Please ensure that you correctly installed v26 and restarted gnome-shell afterwards. This is working fine for me on Ubuntu 18.04:

![Peek 2019-11-17 10-09](https://user-images.githubusercontent.com/33044886/69009432-15a71c00-0923-11ea-8d28-56c69ea8347e.gif)

Thanks!

**Comment by 16NoCo** [comment]
Indeed !
I searched the issues without finding, and waited for the update to post this (and I thought I restarted gnome-shell, but apparently not).
Thank you
