### ISSUE TITLE
No data error when resuming from lock screen

### ISSUE THREAD

**Issue by SuperEvenSteven** [home-sweet-gnome/dash-to-panel#821]
Hi,

When resuming from the lock screen I notice a gnome notification error saying that the dash panel received no data.

![Screenshot from 2019-11-22 09-01-54](https://user-images.githubusercontent.com/460548/69380919-a7d66800-0d07-11ea-9449-4ae963dad68f.png)

Ubuntu 16.04
Gnome v3.18.2
Dash to panel v26

Thanks

**Comment by charlesg99** [comment]
Hello Stephen, this is caused by the update check that occurs when you return from the lock screen. Not sure why this happens on 3.18. How did you get 3.18 anyway? I'd like to install it and see if I can reproduce the issue, seems like there is a network issue when the check occurs. Does the error also show up if you go in the "About" tab of the extension settings and click on "Check now"?

![image](https://user-images.githubusercontent.com/33044886/69486812-bca51f80-0e1d-11ea-8a4f-c314a6adca24.png)

You could disable the "periodically check for updates" option to stop that message from appearing. I guess we could also remove the error entirely as it doesn't provide much. Thanks!

**Comment by SuperEvenSteven** [comment]
Thanks @charlesg99, that was the issue. The same error notificaiton appeared when I clicked the 'Check now' button also. I'm running Ubuntu 16.04 which would be why my gnome shell version is so old. Please note my connection is behind a corporate proxy with ssl-inspection if you still end up replicating the issue. I'm happy to leave the  periodic check for updates disabled as you advised.
