### ISSUE TITLE
Panel is above "always on top" windows

### ISSUE THREAD

**Issue by str225** [home-sweet-gnome/dash-to-panel#838]
If Intellihide is enabled and configured to only hide from focused windows: the panel will still be above from "always on top" windows. I expected the panel would be behind the window, or keep hidden.

![](https://user-images.githubusercontent.com/38595480/71320227-17ff1780-2487-11ea-8f31-51c80534a7f2.png)
Panel is above mpv, although it was set to "Always on Top"

**Comment by charlesg99** [comment]
Hello str225, yes you are correct, most gnome-shell ui elements are above windows (including the "always on top" ones) and since that window isn't "focused", we ignore it. Maybe we could add an option to ignore the "always on top" windows as well? Thanks!

**Comment by charlesg99** [comment]
I'm going to close as this is an expected gnome-shell behavior e.g. the same happens with the default top panel. It would be possible to optionally alter it, but at this point I don't think there is much interest in doing so. Thanks!

**Comment by HubKing** [comment]
In my opinion, if implementing it does not require a lot of effort, having it can be helpful, especially when the screen is small like a laptop.  For example, I want to view a picture-to-picture mode video whilst doing other tasks, and it saves a little bit of screen space if I could place the video above the part of the task bar where I do not have to look at for the moment.

If the rationale is that "it is not an expected behaviour", I think that may not be correct. I have just tested the behaviours on Windows 11, KDE Plasma, LXDE, and on all of them, if I enable "Always on Top", the window goes above the task bar. In fact, I am used to this when using Windows. On stock Gnome, such widow does not go above the thin black status bar, but I think Gnome's status bar is a little bit different semantically. Gnome's is a status bar, but on other aforementioned OS/DE's, they are task bar. Dash to Panel is more like a task bar than a status bar, when users who are accustomed to task bar from another OS/DE came to Gnome and installed Dash to Panel to have a task bar, maybe they want a similar behaviour of the task bar they are used to, rather than that of Gnome's status bar.
