### ISSUE TITLE
Multiple notification icons per row in vertical orientation

### ISSUE THREAD

**Issue by ipsingh06** [home-sweet-gnome/dash-to-panel#846]
I'm really loving the Vertical Orientation feature, so thanks for that!

One suggestion I have is showing multiple notification tray icons in a single row when using vertical orientation. Currently it stacks them and wastes space:
![d2p_vertical_tray](https://user-images.githubusercontent.com/12875506/71797740-2b23f280-3004-11ea-9a9a-0249d6792943.png)

**Comment by charlesg99** [comment]
Hello ipsingh06! As a quick solution, maybe you could widen your panel to accommodate all icons in a row? Which extension are you using to display the tray icons? Since the more popular ones (TopIcon Plus and AppIndicator) are fairly common, maybe we could treat them differently to get a better display.

Currently, for extensions added to the panel, we simply check if it fits horizontally and if it doesn't, we set their containers as "vertical". Not much else we can do as extensions (which are all designed for an horizontal layout) can add pretty much anything in their containers, so we would need to adjust to specific extensions according to their specific layouts.

Thanks!

**Comment by ipsingh06** [comment]
Hi @charlesg99,

I am using AppIndicator which comes preinstalled with Ubuntu 19.10. Unfortunately panel width has no effect on the layout.

 It makes sense that DashToPanel has no control over the layout. In any case, I'm not too bothered by the current layout, this was just a nice to have. I'll close this request.

Thanks!

**Comment by charlesg99** [comment]
Not sure why that is, maybe you could try Topicon Plus? This is what it looks like on mine:

![image](https://user-images.githubusercontent.com/33044886/72212635-74b18900-34ad-11ea-8d83-c4f99ff556b7.png)

![image](https://user-images.githubusercontent.com/33044886/72212632-682d3080-34ad-11ea-902f-3ff9aa038951.png)

Thanks!
