### ISSUE TITLE
Panel doesn't display properly on secondary monitor

### ISSUE THREAD

**Issue by ddtuan99** [home-sweet-gnome/dash-to-panel#871]
Hi, i'm using version 18-1 (available on Debian 10 stable repository). 

`Display panels on all monitor` only displays well on primary monitor. In the secondary monitor, the panel is like transparent. When i right click on the panel it pop the menu that supposed to show when i right click the desktop. The panel is actually there, because when i hover at the begining of it, the preview show up, it is the window list there. 

Here is my settings: https://privatebin.net/?0961a68cf70c2436#CMQz7C5EEaWqRTTvaE5vF4tMLu69TAN2GNYpG2Qgzq33

So the panel did show on the secondary monitor but it just appear as a black bar, nothing more.

Does anyone know how to fix it? Many thanks!

Update: i install version 26 and the issue is still there.

**Comment by jderose9** [comment]
Hi @ddtuan99. Sorry you are having an issue. Would you mind to provide a screenshot of what you are observing? Thank you!

**Comment by charlesg99** [comment]
Hello, v26 seems to be working fine for me:

![image](https://user-images.githubusercontent.com/33044886/75046497-312a4180-5493-11ea-8298-354e9e6a3277.png)

Could you disable all of your other extensions, restart gnome-shell and then try again?

Thanks!

**Comment by ddtuan99** [comment]
@jderose9 @charlesg99 v26 actually works fine when i restart. But i really want to use v18 which is on Debian's main repository. I did disable other extesions (not install anything else beside those shipped with gnome).

Here is screenshot of the issue with v18 (i use different size monitors).
![Screenshot from 2020-02-22 10-12-00](https://user-images.githubusercontent.com/48643969/75085452-08ba4a00-555c-11ea-8748-2e964a027ed5.png)

**Comment by charlesg99** [comment]
Sorry, but v18 came out when 3.30 (Debian's version) was the latest gnome-shell version and this issue wasn't present. My guess is that, since then, Clutter was updated in Debian's repo, creating this issue. Anyway, there is no way for us to update the dtp version in Debian's repository. Maybe you could fill an issue on Debian bugtracker.

I would normally have declined trying to fix such an old dtp version, but you're in luck as the fix was obvious. So, the best we can do is manually fix your issue, just run:

`sudo sed -i 's/this.delegate._allocate(null, box, flags);/this.set_allocation(box, flags);this.delegate._allocate(null, box, flags);/' /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/panel.js`

@jderose9 I would close this.

Thanks!
