### ISSUE TITLE
"Show Applications" - After Update - Small Icons

### ISSUE THREAD

**Issue by invaderleige** [home-sweet-gnome/dash-to-panel#913]
**Describe the bug**
Since the latest update from https://extensions.gnome.org/extension/1160/dash-to-panel/, when clicking on "Show Applications" the icons for all applications are too tiny to recognize easily.  When I disable/turn-off Dash to Panel, it works fine.  Before the update, I did not have this issue.

**Linux distribution and version**
Ubuntu 18.04.4 LTS

**GNOME Shell version**
GNOME Shell 3.28.4

**Dash-to-Panel version**
Version 31

**Where was Dash-to-Panel installed from?**
https://extensions.gnome.org/extension/1160/dash-to-panel/

**Screenshots / Video captures**
_Current after the update_
![Current](https://user-images.githubusercontent.com/62735468/77722496-df0d9c00-6fbb-11ea-9c1f-22cbbbac68a4.jpg)

_Previous before the update_
![Previous](https://user-images.githubusercontent.com/62735468/77722507-e92f9a80-6fbb-11ea-9d75-e62ee9d35862.jpg)
NOTE: yes this screenshot has the Dash to Panel turned off, but it was the only way to show what it looked like before with the icons.  So ignore how the panel looks at the top and side.

**Comment by charlesg99** [comment]
Hello invaderleige, this looks like #905 although the issue was happening on 3.36 and I could reproduce it. I'm also on Ubuntu 18.04 and I can't replicate what you're seeing using v31 or the latest master. I tried with one and two monitors as well as xorg and wayland.

Did you restart gnome-shell following the dash to panel update? If not, try that first. If that doesn't help, please try to disable your other extensions, then restart gnome-shell to see if it could be a conflict. Thanks!

**Comment by invaderleige** [comment]
That seemed to fix the issue!  So sorry I didn't think to do this before hand.
