### ISSUE TITLE
Extension order after lockscreen

### ISSUE THREAD

**Issue by mohegan** [home-sweet-gnome/dash-to-panel#930]
**Describe the bug**
After unlock the screen, the Gnome-Shutdown-Button (another extension I use : [https://extensions.gnome.org/extension/1056/gnome-shutdown-button/](url)) change is position between Show Desktop Button.

Before lock the screen, at startup, the Gnome-Shutdown-Button is on the left of the Show Desktop Button. After lockscreen, the two buttons are inverted (Gnome-Shudown-Button at right of Show Desktop Button).

**Linux distribution and version**
Ubuntu 20.04

**GNOME Shell version**
3.36.0

**Dash-to-Panel version**
31

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
If applicable, add screenshots or a link to a video capture to help explain your problem.

**Additional Info**
![Capture d’écran de 2020-04-02 23-15-25](https://user-images.githubusercontent.com/635456/78300679-2b1a8c80-7538-11ea-9f37-011f50f2da4d.png)
![Capture d’écran de 2020-04-02 23-15-42](https://user-images.githubusercontent.com/635456/78300684-2c4bb980-7538-11ea-8030-f6ac8f3ce68b.png)

**Comment by jderose9** [comment]
@mohegan Unfortunately, I don't know what a great solution would be here. The Show desktop button gets inserted at the far right position, and so does the power button from this other extension, and whichever when gets loaded last will "win".

We can detect if additional items have been added to the panel, but so far we've avoided aggressively trying to place dash-to-panel components, so that the extensions don't end up fighting over positioning, and because I'm not certain there aren't also cases where you would want the reverse behavior.

**Comment by jderose9** [comment]
I'm going to close this one in favor of #931 .

**Comment by mohegan** [comment]
I have tried to force position but It doesn't work.
In Dash-to-panel, I modify panel.js : 
```
//this._rightBox.insert_child_at_index(this._showDesktopButton, this._rightBox.get_children().length);

this._rightBox.insert_child_at_index(this._showDesktopButton, -2);
```

And, in gnome-shutdown-button, I modify extension.js :
```
Main.panel._rightBox.insert_child_at_index(button, -1);

//Main.panel._rightBox.insert_child_at_index(button, children().length);
```

After that, the problem is the same.

**Comment by jderose9** [comment]
The index is a positive number, but yes the behavior would still be similar.. Because Show Desktop button doesn't exist if the other extension loads first, and the power button doesnt exist if dash-to-panel loads first. You could update the other extension to check to see if the Show Desktop button exists in `this._rightBox`, and if it does, insert the power button at `children().length-1` (and if not, children().length).
