### ISSUE TITLE
Fedora 32 (Gnome 3.36.1): Auto-hide intelligent option not working in Xorg like Wayland

### ISSUE THREAD

**Issue by calotam** [home-sweet-gnome/dash-to-panel#946]
I have configurated a left panel with auto-hide intelligent option.
- In Wayland, when the mouse pointer is on the desk, the left panel is auto hide. That's ok.
- **In Xorg, when the mouse pointer is on the desk, the left panel is visible. That's wrong**.

**Comment by charlesg99** [comment]
Hello calotam, what do you mean by "is on the desk"? You mean the desktop background? So far I can't reproduce the issue, it behaves the same on Xorg and Wayland for me. Thanks!

**Comment by calotam** [comment]
I mean when the mouse pointer is outsie other windows (I have window focus with mouse pointer) and it is only on desktop background, then in Wayland left panel auto-hide and I can see my left icons. When the mouse pointer is on a window that it is not over left panel, then the panel is not hidden. The behaviour is the same without window focus on mouse over.

In Xorg, when i do left click press with mouse the panel is not hidden. In wayland is hidden.

**Comment by charlesg99** [comment]
Could you maybe add a screen capture of what you're seeing? I still can't reproduce that. Thanks!

**Comment by calotam** [comment]
Hello, this is my capute on X11. It's a part of my desktop. Desktop capture has no windows and as I said, in X11 left dash panel is shown over de icons (I have auto-hide intelligent opcion selected). In Wayland left dash panel is auto-hide.

![Captura de pantalla de 2020-04-08 19-29-18](https://user-images.githubusercontent.com/57635310/78814768-7bc63580-79cf-11ea-96b2-fbca3653f05c.png)

**Comment by charlesg99** [comment]
So if I understand correctly:
 - on wayland, when the desktop has focus, icons are considered as "windows" and they obstruct the panel so the panel hides 
- on xorg, when the desktop has focus, icons are **not** considered as windows so the panel stays visible

Correct? Seems like a bug in the extension rendering the desktop icons if you ask me. What extension is that? Thanks!

**Comment by calotam** [comment]
It's correct.
The extension desktop icons i have is 'Desktop Icons NG (DING)'.

**Comment by charlesg99** [comment]
I got to reproduce the issue with "Desktop Icons NG (DING)". Seems like no matter where the icons are, on wayland when the desktop has focus the panel hides. At first I thought it was something like #356 reappearing, but it only happens when the desktop icons extension is enabled.

I had a quick glance at their code and they launch a gjs process that spawns a window on which they're drawing the icons. I didn't dig very deep, but there clearly is a difference between how they handle that window on xorg and wayland. At that point, I would encourage you to open an issue on [their repository](https://gitlab.com/rastersoft/desktop-icons-ng/-/issues). Thanks!

**Comment by calotam** [comment]
Ok, thank you very much!!!
