### ISSUE TITLE
Issue with intellihide

### ISSUE THREAD

**Issue by YuriHeiko** [home-sweet-gnome/dash-to-panel#956]
**Describe the bug**
I have an issue with intellihide. I have two monitors, on the second monitor it works perfectly all the time. On the prime monitor it works fine until there are no open app windows. When I open any app (no matter full-screen or not) the panel started to open and close. Please watch the video.

**Linux distribution and version**
Ubuntu 18.04

**GNOME Shell version**
GNOME Shell 3.28.4

**Dash-to-Panel version**
version: 35

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**
[Video capture](https://vimeo.com/406981165)

**Comment by charlesg99** [comment]
Hello Yuri, could you please try to disable all of your extensions, restart gnome-shell and then see if the issue persists. I'm also on Ubuntu 18.04 with 2 monitors and I've never seen this. I tried to reproduce it while doing the same as shown in your video, without success. If it persists after restarting gnome-shell with your other extensions disabled, please provide your dash to panel settings and the exact steps to reproduce the issue. Thanks!

**Comment by YuriHeiko** [comment]
You are absolutely right. The culprit was the Hide Top Bar extension. Sorry for disturbing you and thank you for your great extension!

**Comment by charlesg99** [comment]
Glad it's working now!

**Comment by bittner** [comment]
Hide Top Bar makes the panel disappear oddly when intellihide is active on both extensions. This is because Dash to Panel integrates the top panel into a single panel, which is then affected as a whole by the actions the former extension triggers.

Could the Dash to Panel settings detect that the Hide Top Panel extension is active and warn about the conflict? It might suggest to deactivate the Hide Top Panel extension. That would help.
