### ISSUE TITLE
Option for super to open applications instead of overview

### ISSUE THREAD

**Issue by pmuybae** [home-sweet-gnome/dash-to-panel#964]
I'd like an option so super opens the application menu (like clicking the grid icon in the bottom left), instead of opening up the overview, since I don't use that at all.

**Comment by charlesg99** [comment]
Hello pornismuybae, I'm not sure if overriding the super key with another existing system operation is a good idea, since you can already assign the super key to show the applications ([with a bit of doing](https://unix.stackexchange.com/questions/388238/how-to-set-super-windows-key-to-show-all-applications-menu-in-gnome-de)). I'm mostly worried about competing with other extensions that really have a valid use case for overriding the super key, like Arc-Menu for instance who shows its own menu with it. Thanks!
