### ISSUE TITLE
Feature Request: Smarter Preview Timings on Hover

### ISSUE THREAD

**Issue by alex285** [home-sweet-gnome/dash-to-panel#973]
Hello, I'm describing this option:
![dtp-1](https://user-images.githubusercontent.com/11244308/80362530-77cd5b00-888b-11ea-8c47-ba5ffd9a6722.png)

**A small suggestion** is that I believe hover on 100ms triggers too fast, and it becomes quite annoying when accidentally that happens, so maybe that default should be 300-400ms? Specially because navigating on DtP options isn't straightforward for people due to the large number of them

**And the actual issue.** I set the hover value to 400ms, but now the problem is that navigating to the neighbor icon/window-preview it again needs 400ms to trigger; So the feature request is if we can set the initial trigger to any timing (eg 400ms), but after that point the next preview should open at 100ms

![dtp-2](https://user-images.githubusercontent.com/11244308/80363339-c3cccf80-888c-11ea-98ea-adbdb62cc51f.png)
For example on the above image, navigating from Dash To Panel option preview to Chrome preview next to it, it needs 400ms, but it would make more sense if it gets 100ms, since most probably that action isn't triggered accidentally, but that's what we want to do. 

If we assume that the neighbor icon hasn't a preview (eg not an open app), and as long as the cursor stays on DtP surface, the very next preview perhaps should also opens in 100ms

**Comment by charlesg99** [comment]
Hello Alex! Yes I agree with both of your points. I changed it locally to try it out and I like it, but I wonder "what if" people did set this timeout to something smaller than 100. If so, forcing the delay to 100 when hovering on another icon while the preview is already opened might bother them as they would expect the menu to move instantly. At the same time, I really don't want to add another setting for this and 100 looks perfect to me (I don't like it when it is set to 0). What do you think? @jderose9?

Thanks!

**Comment by charlesg99** [comment]
A new settings to control the 100 timeout when the preview menu is already opened was added to master and the default of the initial timeout was upped to 300. The new setting isn't available through the UI though, only using dconf as I'm pretty confident it'll be fine for the vast majority of users. Let me know what you think! Thanks!

**Comment by jderose9** [comment]
@charlesg99 That all sounds good to me. Maybe we should do the lesser of 100 and the original setting when the preview is already open?

**Comment by charlesg99** [comment]
@jderose9 Yes absolutely, much better than introducing a new hidden setting. Master has been updated to reflect this, thanks!

**Comment by evertonstz** [comment]
Another day, another good alex request.
@charlesg99 I think a good way to handle this problem would be something like this:
Lets call the timeout when opening a preview just "timeout" and when a preview is already opened "opened timeout".
- If a user set "timeout" to something bigger than 100ms, keep the "opened timeout" constant at 100ms;
- If a user set "timeout" to something smaller than 100ms, set the "opened timeout" to the same value as "timeout".

So a "timeout" of 20ms would set "opened timeout" also to 20ms, but a "timeout" of 200ms, would keep the "opened timeout" at 100ms.

I think it's a good solution, since timings smaller than 100ms are so fast I really doubt it would annoy people having the same timing for "opened timeout", while having a "opened timeout" that's actually bigger than "timeout" could actually annoy people, specially if "timeout" is set to a small value making the gap bigger.

**Comment by charlesg99** [comment]
Thank you for your input evertonstz, what you describe is exactly what we ended up doing following Jason's suggestion. I'll close this now as the modification is on master, thanks!
