### ISSUE TITLE
Tray icons misplaced after logon/screen unlock

### ISSUE THREAD

**Issue by throwable** [home-sweet-gnome/dash-to-panel#974]
Dear developers,

I've tried to reduce spacing between tray icons by adjusting padding parameters in "Fine-Tune" tab (4px for all paddings). But after restarting the session or doing screen unlock the icons are shown misplaced with the theme's default huge spacing between them. When then I hover mouse above each one the space is reduced to adjusted size.

**Versions**
Ubuntu 20.04, Gnome 3.36.1, Dash-to-panel v35

**Screenshots / Video captures**
Normal spacing with paddings adjusted:
![image](https://user-images.githubusercontent.com/1713694/80490112-2bece580-8961-11ea-9ec1-c2dbd4b82cd1.png)
Right after screen unlock/session logon (misplaced):
![image](https://user-images.githubusercontent.com/1713694/80490171-40c97900-8961-11ea-8e8b-c17a75192ddd.png)

Thanx a lot!

**Comment by charlesg99** [comment]
Hello, yes this is a long standing [gnome-shell issue](https://gitlab.gnome.org/GNOME/gnome-shell/issues/1708) unfortunately. We added a workaround for it on 3.34 (see #739), but it seems like it doesn't work on 3.36, at least not for the Ubuntu tray extension. At this point, I would push on gnome-shell side and see if they decide to merge [the fix](https://gitlab.gnome.org/verdre/gnome-shell/-/commit/f46955f51979c4206551f3e7ef8785ee7ed14a63) instead of adding yet more hacky code. Thanks!

**Comment by charlesg99** [comment]
I was curious and had a look at this. I ended up modifying our workaround for this and pushed a modification to the master branch. It seems to be working with the Ubuntu tray icons now, could you please install from source and confirm that it fixes the issue on your machine as well? Thanks!

**Comment by elliotwutingfeng** [comment]
Versions
5.6.7-1-MANJARO, Gnome 3.36.1, Dash-to-panel v37 (from gnome extensions website)

I do not have this issue on Manjaro.

**Comment by throwable** [comment]
> I was curious and had a look at this. I ended up modifying our workaround for this and pushed a modification to the master branch. It seems to be working with the Ubuntu tray icons now, could you please install from source and confirm that it fixes the issue on your machine as well? Thanks!

Ok, I've just installed it from the source and I confirm it works as expected. Thanx a lot!
